"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from unittest.mock import MagicMock

from openapi_client.api.instrumentcategories_api import InstrumentcategoriesApi
from openapi_client.api_client import ApiClient


class TestInstrumentcategoriesApi:
    """InstrumentcategoriesApi unit tests"""

    def setup_method(self):
        """Set up test fixtures before each test method."""
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = InstrumentcategoriesApi(api_client=self.api_client)

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self):
        """InstrumentcategoriesApi can be created with a mock ApiClient."""
        assert isinstance(self.api, InstrumentcategoriesApi)
        assert self.api.api_client is self.api_client

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_create_instrument_category(self):
        assert callable(getattr(self.api, "create_instrument_category", None))

    def test_has_delete_instrument_category(self):
        assert callable(getattr(self.api, "delete_instrument_category", None))

    def test_has_update_instrument_category(self):
        assert callable(getattr(self.api, "update_instrument_category", None))

    def test_has_with_http_info_variants(self):
        for method in (
            "create_instrument_category_with_http_info",
            "delete_instrument_category_with_http_info",
            "update_instrument_category_with_http_info",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    def test_has_without_preload_content_variants(self):
        for method in (
            "create_instrument_category_without_preload_content",
            "delete_instrument_category_without_preload_content",
            "update_instrument_category_without_preload_content",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    # ------------------------------------------------------------------ #
    #  _create_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_create_instrument_category_serialize(self, **overrides):
        """Helper to call _create_instrument_category_serialize with defaults."""
        defaults = {
            "instrument_category_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._create_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_create_instrument_category_serialize_method_and_path(self):
        """_create_instrument_category_serialize uses POST /instrument-categories."""
        kw = self._call_create_instrument_category_serialize()
        assert kw["method"] == "POST"
        assert kw["resource_path"] == "/instrument-categories"

    def test_create_instrument_category_serialize_bearer_auth(self):
        """_create_instrument_category_serialize requires bearerAuth."""
        kw = self._call_create_instrument_category_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_create_instrument_category_serialize_body(self):
        """_create_instrument_category_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_create_instrument_category_serialize(
            instrument_category_request=mock_body
        )
        assert kw["body"] is mock_body

    def test_create_instrument_category_serialize_no_path_params(self):
        """_create_instrument_category_serialize has no path parameters."""
        kw = self._call_create_instrument_category_serialize()
        assert kw["path_params"] == {}

    def test_create_instrument_category_serialize_no_query_params(self):
        """_create_instrument_category_serialize has no query parameters."""
        kw = self._call_create_instrument_category_serialize()
        assert kw["query_params"] == []

    # ------------------------------------------------------------------ #
    #  _delete_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_delete_instrument_category_serialize(self, **overrides):
        """Helper to call _delete_instrument_category_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._delete_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_delete_instrument_category_serialize_method_and_path(self):
        """_delete_instrument_category_serialize uses DELETE /instrument-categories/{metquayId}."""
        kw = self._call_delete_instrument_category_serialize()
        assert kw["method"] == "DELETE"
        assert kw["resource_path"] == "/instrument-categories/{metquayId}"

    def test_delete_instrument_category_serialize_bearer_auth(self):
        """_delete_instrument_category_serialize requires bearerAuth."""
        kw = self._call_delete_instrument_category_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_delete_instrument_category_serialize_no_body(self):
        """_delete_instrument_category_serialize sends no body."""
        kw = self._call_delete_instrument_category_serialize()
        assert kw["body"] is None

    def test_delete_instrument_category_serialize_path_params(self):
        """_delete_instrument_category_serialize passes path parameters."""
        kw = self._call_delete_instrument_category_serialize(
            metquay_id=99,
        )
        assert kw["path_params"] == {
            "metquayId": 99,
        }

    def test_delete_instrument_category_serialize_no_query_params(self):
        """_delete_instrument_category_serialize has no query parameters."""
        kw = self._call_delete_instrument_category_serialize()
        assert kw["query_params"] == []

    # ------------------------------------------------------------------ #
    #  _update_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_update_instrument_category_serialize(self, **overrides):
        """Helper to call _update_instrument_category_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "instrument_category_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._update_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_update_instrument_category_serialize_method_and_path(self):
        """_update_instrument_category_serialize uses PUT /instrument-categories/{metquayId}."""
        kw = self._call_update_instrument_category_serialize()
        assert kw["method"] == "PUT"
        assert kw["resource_path"] == "/instrument-categories/{metquayId}"

    def test_update_instrument_category_serialize_bearer_auth(self):
        """_update_instrument_category_serialize requires bearerAuth."""
        kw = self._call_update_instrument_category_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_update_instrument_category_serialize_body(self):
        """_update_instrument_category_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_update_instrument_category_serialize(
            instrument_category_request=mock_body
        )
        assert kw["body"] is mock_body

    def test_update_instrument_category_serialize_path_params(self):
        """_update_instrument_category_serialize passes path parameters."""
        kw = self._call_update_instrument_category_serialize(
            metquay_id=99,
        )
        assert kw["path_params"] == {
            "metquayId": 99,
        }

    def test_update_instrument_category_serialize_no_query_params(self):
        """_update_instrument_category_serialize has no query parameters."""
        kw = self._call_update_instrument_category_serialize()
        assert kw["query_params"] == []
