"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
from unittest.mock import MagicMock

from openapi_client.api_client import ApiClient

from openapi_client.api.authenticate_api import AuthenticateApi


class TestAuthenticateApi(unittest.TestCase):
    """AuthenticateApi unit tests"""

    def setUp(self) -> None:
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = AuthenticateApi(api_client=self.api_client)

    def tearDown(self) -> None:
        pass

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self) -> None:
        """AuthenticateApi can be created with a mock ApiClient."""
        self.assertIsInstance(self.api, AuthenticateApi)
        self.assertIs(self.api.api_client, self.api_client)

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_get_access_token(self) -> None:
        self.assertTrue(callable(getattr(self.api, "get_access_token", None)))

    def test_has_with_http_info_variants(self) -> None:
        for method in ("get_access_token_with_http_info",):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    def test_has_without_preload_content_variants(self) -> None:
        for method in ("get_access_token_without_preload_content",):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    # ------------------------------------------------------------------ #
    #  _get_access_token_serialize
    # ------------------------------------------------------------------ #
    def _call_get_access_token_serialize(self, **overrides):
        """Helper to call _get_access_token_serialize with defaults."""
        defaults = {
            "authentication_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._get_access_token_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_get_access_token_serialize_method_and_path(self) -> None:
        """_get_access_token_serialize uses POST /authenticate."""
        kw = self._call_get_access_token_serialize()
        self.assertEqual(kw["method"], "POST")
        self.assertEqual(kw["resource_path"], "/authenticate")

    def test_get_access_token_serialize_no_auth(self) -> None:
        """_get_access_token_serialize uses no auth."""
        kw = self._call_get_access_token_serialize()
        self.assertEqual(kw["auth_settings"], [])

    def test_get_access_token_serialize_body(self) -> None:
        """_get_access_token_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_get_access_token_serialize(authentication_request=mock_body)
        self.assertIs(kw["body"], mock_body)

    def test_get_access_token_serialize_no_path_params(self) -> None:
        """_get_access_token_serialize has no path parameters."""
        kw = self._call_get_access_token_serialize()
        self.assertEqual(kw["path_params"], {})

    def test_get_access_token_serialize_no_query_params(self) -> None:
        """_get_access_token_serialize has no query parameters."""
        kw = self._call_get_access_token_serialize()
        self.assertEqual(kw["query_params"], [])


if __name__ == "__main__":
    unittest.main()
