"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
from unittest.mock import MagicMock

from openapi_client.api_client import ApiClient

from openapi_client.api.customerinstruments_api import CustomerinstrumentsApi


class TestCustomerinstrumentsApi(unittest.TestCase):
    """CustomerinstrumentsApi unit tests"""

    def setUp(self) -> None:
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = CustomerinstrumentsApi(api_client=self.api_client)

    def tearDown(self) -> None:
        pass

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self) -> None:
        """CustomerinstrumentsApi can be created with a mock ApiClient."""
        self.assertIsInstance(self.api, CustomerinstrumentsApi)
        self.assertIs(self.api.api_client, self.api_client)

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_create_customer_instrument(self) -> None:
        self.assertTrue(callable(getattr(self.api, "create_customer_instrument", None)))

    def test_has_delete_customer_instrument(self) -> None:
        self.assertTrue(callable(getattr(self.api, "delete_customer_instrument", None)))

    def test_has_get_customer_instruments(self) -> None:
        self.assertTrue(callable(getattr(self.api, "get_customer_instruments", None)))

    def test_has_update_customer_instrument(self) -> None:
        self.assertTrue(callable(getattr(self.api, "update_customer_instrument", None)))

    def test_has_with_http_info_variants(self) -> None:
        for method in (
            "create_customer_instrument_with_http_info",
            "delete_customer_instrument_with_http_info",
            "get_customer_instruments_with_http_info",
            "update_customer_instrument_with_http_info",
        ):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    def test_has_without_preload_content_variants(self) -> None:
        for method in (
            "create_customer_instrument_without_preload_content",
            "delete_customer_instrument_without_preload_content",
            "get_customer_instruments_without_preload_content",
            "update_customer_instrument_without_preload_content",
        ):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    # ------------------------------------------------------------------ #
    #  _create_customer_instrument_serialize
    # ------------------------------------------------------------------ #
    def _call_create_customer_instrument_serialize(self, **overrides):
        """Helper to call _create_customer_instrument_serialize with defaults."""
        defaults = {
            "customer_instrument_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._create_customer_instrument_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_create_customer_instrument_serialize_method_and_path(self) -> None:
        """_create_customer_instrument_serialize uses POST /customer-instrument-details."""
        kw = self._call_create_customer_instrument_serialize()
        self.assertEqual(kw["method"], "POST")
        self.assertEqual(kw["resource_path"], "/customer-instrument-details")

    def test_create_customer_instrument_serialize_bearer_auth(self) -> None:
        """_create_customer_instrument_serialize requires bearerAuth."""
        kw = self._call_create_customer_instrument_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_create_customer_instrument_serialize_body(self) -> None:
        """_create_customer_instrument_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_create_customer_instrument_serialize(
            customer_instrument_request=mock_body
        )
        self.assertIs(kw["body"], mock_body)

    def test_create_customer_instrument_serialize_no_path_params(self) -> None:
        """_create_customer_instrument_serialize has no path parameters."""
        kw = self._call_create_customer_instrument_serialize()
        self.assertEqual(kw["path_params"], {})

    def test_create_customer_instrument_serialize_no_query_params(self) -> None:
        """_create_customer_instrument_serialize has no query parameters."""
        kw = self._call_create_customer_instrument_serialize()
        self.assertEqual(kw["query_params"], [])

    # ------------------------------------------------------------------ #
    #  _delete_customer_instrument_serialize
    # ------------------------------------------------------------------ #
    def _call_delete_customer_instrument_serialize(self, **overrides):
        """Helper to call _delete_customer_instrument_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._delete_customer_instrument_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_delete_customer_instrument_serialize_method_and_path(self) -> None:
        """_delete_customer_instrument_serialize uses DELETE /customer-instrument-details/{metquayId}."""
        kw = self._call_delete_customer_instrument_serialize()
        self.assertEqual(kw["method"], "DELETE")
        self.assertEqual(
            kw["resource_path"], "/customer-instrument-details/{metquayId}"
        )

    def test_delete_customer_instrument_serialize_bearer_auth(self) -> None:
        """_delete_customer_instrument_serialize requires bearerAuth."""
        kw = self._call_delete_customer_instrument_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_delete_customer_instrument_serialize_no_body(self) -> None:
        """_delete_customer_instrument_serialize sends no body."""
        kw = self._call_delete_customer_instrument_serialize()
        self.assertIsNone(kw["body"])

    def test_delete_customer_instrument_serialize_path_params(self) -> None:
        """_delete_customer_instrument_serialize passes path parameters."""
        kw = self._call_delete_customer_instrument_serialize(
            metquay_id=99,
        )
        self.assertEqual(
            kw["path_params"],
            {
                "metquayId": 99,
            },
        )

    def test_delete_customer_instrument_serialize_no_query_params(self) -> None:
        """_delete_customer_instrument_serialize has no query parameters."""
        kw = self._call_delete_customer_instrument_serialize()
        self.assertEqual(kw["query_params"], [])

    # ------------------------------------------------------------------ #
    #  _get_customer_instruments_serialize
    # ------------------------------------------------------------------ #
    def _call_get_customer_instruments_serialize(self, **overrides):
        """Helper to call _get_customer_instruments_serialize with defaults."""
        defaults = {
            "workspace_code": None,
            "first": None,
            "limit": None,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._get_customer_instruments_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_get_customer_instruments_serialize_method_and_path(self) -> None:
        """_get_customer_instruments_serialize uses GET /customer-instrument-details."""
        kw = self._call_get_customer_instruments_serialize()
        self.assertEqual(kw["method"], "GET")
        self.assertEqual(kw["resource_path"], "/customer-instrument-details")

    def test_get_customer_instruments_serialize_bearer_auth(self) -> None:
        """_get_customer_instruments_serialize requires bearerAuth."""
        kw = self._call_get_customer_instruments_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_get_customer_instruments_serialize_no_body(self) -> None:
        """_get_customer_instruments_serialize sends no body."""
        kw = self._call_get_customer_instruments_serialize()
        self.assertIsNone(kw["body"])

    def test_get_customer_instruments_serialize_no_path_params(self) -> None:
        """_get_customer_instruments_serialize has no path parameters."""
        kw = self._call_get_customer_instruments_serialize()
        self.assertEqual(kw["path_params"], {})

    def test_get_customer_instruments_serialize_no_query_when_none(self) -> None:
        """Omits query params when all are None."""
        kw = self._call_get_customer_instruments_serialize()
        self.assertEqual(kw["query_params"], [])

    def test_get_customer_instruments_serialize_workspace_code(self) -> None:
        """Includes workspaceCode query param."""
        kw = self._call_get_customer_instruments_serialize(workspace_code="test_value")
        self.assertIn(("workspaceCode", "test_value"), kw["query_params"])

    def test_get_customer_instruments_serialize_first(self) -> None:
        """Includes first query param."""
        kw = self._call_get_customer_instruments_serialize(first=10)
        self.assertIn(("first", 10), kw["query_params"])

    def test_get_customer_instruments_serialize_limit(self) -> None:
        """Includes limit query param."""
        kw = self._call_get_customer_instruments_serialize(limit=10)
        self.assertIn(("limit", 10), kw["query_params"])

    # ------------------------------------------------------------------ #
    #  _update_customer_instrument_serialize
    # ------------------------------------------------------------------ #
    def _call_update_customer_instrument_serialize(self, **overrides):
        """Helper to call _update_customer_instrument_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "customer_instrument_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._update_customer_instrument_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_update_customer_instrument_serialize_method_and_path(self) -> None:
        """_update_customer_instrument_serialize uses PUT /customer-instrument-details/{metquayId}."""
        kw = self._call_update_customer_instrument_serialize()
        self.assertEqual(kw["method"], "PUT")
        self.assertEqual(
            kw["resource_path"], "/customer-instrument-details/{metquayId}"
        )

    def test_update_customer_instrument_serialize_bearer_auth(self) -> None:
        """_update_customer_instrument_serialize requires bearerAuth."""
        kw = self._call_update_customer_instrument_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_update_customer_instrument_serialize_body(self) -> None:
        """_update_customer_instrument_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_update_customer_instrument_serialize(
            customer_instrument_request=mock_body
        )
        self.assertIs(kw["body"], mock_body)

    def test_update_customer_instrument_serialize_path_params(self) -> None:
        """_update_customer_instrument_serialize passes path parameters."""
        kw = self._call_update_customer_instrument_serialize(
            metquay_id=99,
        )
        self.assertEqual(
            kw["path_params"],
            {
                "metquayId": 99,
            },
        )

    def test_update_customer_instrument_serialize_no_query_params(self) -> None:
        """_update_customer_instrument_serialize has no query parameters."""
        kw = self._call_update_customer_instrument_serialize()
        self.assertEqual(kw["query_params"], [])


if __name__ == "__main__":
    unittest.main()
