"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from pydantic import ValidationError

from openapi_client.models.authentication_request import AuthenticationRequest


class TestAuthenticationRequest(unittest.TestCase):
    """AuthenticationRequest unit tests"""

    _REQUIRED_KWARGS = {
        "access_key": "mqt_live_7xK2pL9nR4tW8yF3",
        "secret_key": "sk_mqt_5hJ8mD2vB6nQ9xK4",
    }

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #
    def test_construction_required_only(self):
        """Test constructing AuthenticationRequest with only required fields."""
        obj = AuthenticationRequest(**self._REQUIRED_KWARGS)
        self.assertEqual(obj.access_key, "mqt_live_7xK2pL9nR4tW8yF3")
        self.assertEqual(obj.secret_key, "sk_mqt_5hJ8mD2vB6nQ9xK4")

    def test_full_construction(self):
        """Test constructing AuthenticationRequest with all non-date fields."""
        obj = AuthenticationRequest(
            access_key="mqt_live_7xK2pL9nR4tW8yF3",
            secret_key="sk_mqt_5hJ8mD2vB6nQ9xK4",
        )
        self.assertIsNotNone(obj)

    def test_optional_fields_default_to_none(self):
        """Test that optional fields without defaults are None."""

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = AuthenticationRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        self.assertIsInstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
            "accessKey": "mqt_live_7xK2pL9nR4tW8yF3",
            "secretKey": "sk_mqt_5hJ8mD2vB6nQ9xK4",
        }
        obj = AuthenticationRequest.from_dict(data)
        self.assertIsNotNone(obj)
        self.assertEqual(obj.access_key, "mqt_live_7xK2pL9nR4tW8yF3")
        self.assertEqual(obj.secret_key, "sk_mqt_5hJ8mD2vB6nQ9xK4")

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        self.assertIsNone(AuthenticationRequest.from_dict(None))

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = AuthenticationRequest(**self._REQUIRED_KWARGS)
        json_str = obj.to_json()
        restored = AuthenticationRequest.from_json(json_str)
        self.assertIsNotNone(restored)

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_missing_access_key_raises(self):
        """Test that missing required 'access_key' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "access_key"}
        with self.assertRaises(ValidationError):
            AuthenticationRequest(**kwargs)

    def test_missing_secret_key_raises(self):
        """Test that missing required 'secret_key' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "secret_key"}
        with self.assertRaises(ValidationError):
            AuthenticationRequest(**kwargs)


if __name__ == "__main__":
    unittest.main()
