"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501



from openapi_client.models.work_response import WorkResponse


class TestWorkResponse:
    """WorkResponse unit tests"""


    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #

    def test_construction_empty(self):
        """Test constructing WorkResponse with no arguments (all optional)."""
        obj = WorkResponse()
        assert obj is not None

    def test_full_construction(self):
        """Test constructing WorkResponse with all non-date fields."""
        obj = WorkResponse(
            id=21568,
            work_no='CAL-2024-021568',
            customer_instrument_id=8234,
            accreditation=True,
            compliance_required=True,
            site_job=False,
            outsource=False,
            customer_specific_requirements='Calibration required at 5 specific points: -20°C, 0°C, 25°C, 50°C, 80°C. Certificate must include measurement uncertainty at 95% confidence level.',
            scope='Full calibration per manufacturer specifications. 5-point verification across all ranges. Includes NIST traceable certificate.',
            certificate_address='Metquay Inc., 123 Innovation Drive, Suite 400, Chicago, IL 60606-1234, United States',
            remarks='Rush order requested by customer. Standard 5-day turnaround reduced to 3 days. Quote #Q-2024-0123 approved.',
            work_flow_type='Calibration',
            sales_order_no='SO-2024-04567',
            workspace_code='NA-HQ',
            sub_con_details='High-voltage calibration subcontracted to PowerCal Labs. Returned on 01-26-2024. Subcontractor PO #PO-2024-8910.',
            customer='Metquay Inc.',
            instrument_name='Fluke 87V Industrial Digital Multimeter',
            instrument_serial_no='FLK-87V-2024-4582',
            instrument_tag_no='METER-LAB-87V-042',
            instrument_barcode='MQ-87V-2024-04582',
            instrument_category_name='Digital Multimeter',
            item_description='Fluke 87V Max Digital Multimeter with NIST certification',
            department_name='Metrology Lab - Electrical',
            status='Finished',
            report_type='Certificate',
            accreditation_type='Accredited',
            procedure='FLUKE-87V-CAL-PROC-Rev4',
            technician='Sandeep Nair',
            revision_no=1,
            certificate_no='MQ-CAL-2024-021568',
            finished_by='Sandeep Nair',
            sales_person='Michael Chen',
            customer_po_no='PO-2024-01234',
            so_description='Rush calibration service - Fluke 87V Multimeter',
            workspace='NA-HQ Electrical Lab',
            job_type='At Lab',
        )
        assert obj is not None


    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = WorkResponse()

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = WorkResponse(
            id=21568,
        )
        d = obj.to_dict()
        assert isinstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = WorkResponse()
        d = obj.to_dict()
        assert "id" not in d
        assert "workNo" not in d
        assert "customerInstrumentId" not in d
        assert "inDate" not in d
        assert "accreditation" not in d
        assert "complianceRequired" not in d
        assert "siteJob" not in d
        assert "outsource" not in d
        assert "customerSpecificRequirements" not in d
        assert "scope" not in d
        assert "certificateAddress" not in d
        assert "remarks" not in d
        assert "workFlowType" not in d
        assert "deliveryDate" not in d
        assert "salesOrderNo" not in d
        assert "workspaceCode" not in d
        assert "subConDetails" not in d
        assert "customer" not in d
        assert "instrumentName" not in d
        assert "instrumentSerialNo" not in d
        assert "instrumentTagNo" not in d
        assert "instrumentBarcode" not in d
        assert "instrumentCategoryName" not in d
        assert "itemDescription" not in d
        assert "departmentName" not in d
        assert "status" not in d
        assert "reportType" not in d
        assert "accreditationType" not in d
        assert "procedure" not in d
        assert "technician" not in d
        assert "workDate" not in d
        assert "dueDate" not in d
        assert "revisionNo" not in d
        assert "certificateNo" not in d
        assert "finishedDate" not in d
        assert "finishedBy" not in d
        assert "salesPerson" not in d
        assert "recommendedDueDate" not in d
        assert "calibratedDate" not in d
        assert "workStartDate" not in d
        assert "customerPoNo" not in d
        assert "soDescription" not in d
        assert "workspace" not in d
        assert "jobType" not in d

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
        }
        obj = WorkResponse.from_dict(data)
        assert obj is not None

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        assert WorkResponse.from_dict(None) is None

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = WorkResponse(
            id=21568,
        )
        json_str = obj.to_json()
        restored = WorkResponse.from_json(json_str)
        assert restored is not None

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
