# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.works_api import WorksApi


class TestWorksApi(unittest.TestCase):
    """WorksApi unit test stubs"""

    def setUp(self) -> None:
        self.api = WorksApi()

    def tearDown(self) -> None:
        pass

    def test_create_work(self) -> None:
        """Test case for create_work

        Create a new work
        """
        pass

    def test_get_works(self) -> None:
        """Test case for get_works

        Get paginated list of works
        """
        pass

    def test_update_work(self) -> None:
        """Test case for update_work

        Update an existing work
        """
        pass


if __name__ == "__main__":
    unittest.main()
