"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from pydantic import ValidationError

from openapi_client.models.customer_instrument_response import (
    CustomerInstrumentResponse,
)


class TestCustomerInstrumentResponse(unittest.TestCase):
    """CustomerInstrumentResponse unit tests"""

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #

    def test_construction_empty(self):
        """Test constructing CustomerInstrumentResponse with no arguments (all optional)."""
        obj = CustomerInstrumentResponse()
        self.assertIsNotNone(obj)

    def test_full_construction(self):
        """Test constructing CustomerInstrumentResponse with all non-date fields."""
        obj = CustomerInstrumentResponse(
            id=8234,
            barcode="MQ-87V-2024-04582",
            company_name="Metquay Inc.",
            instrument_name="Fluke 87V Industrial Digital Multimeter",
            instrument_category="Digital Multimeter",
            item_name="Fluke 87V Digital Multimeter",
            make="Fluke Corporation",
            model="87V Max",
            range="0-1000V DC, 0-750V AC, 0-10A, 0-50MΩ",
            type="True RMS Digital Multimeter",
            tolerance="±0.05% basic DC accuracy",
            serial_no="FLK-87V-2024-4582",
            tag_no="METER-LAB-87V-042",
            control_no="CTL-2024-042",
            calibration_frequency="180",
            workspace_code="NA-HQ",
            calibration_frequency_span="DAY",
            active=True,
            parent_tag_no="SYSTEM-87V-MAIN-001",
            department_name="Metrology Lab - Electrical",
            calibration_cost=185.5,
            is_calibrated_externally=False,
            calibration_vendor="Metquay Calibration Services",
            remarks="High-precision instrument for ISO 17025 accredited calibrations. Requires special handling.",
            instrument_notes="Battery replaced on 12-15-2023. Firmware updated to v2.1. Next firmware check due: 06-2024.",
            is_mobile=True,
            is_calibration_required=True,
            calibration_status="Good",
            received_condition="Good",
            certificate_url="https://certificates.metquay.com/FLK-87V-2024-4582-20240122.pdf",
            project_names=[
                "ISO-17025-2024-Upgrade",
                "Lab-Certification-Q2",
                "Customer-Project-Acme-001",
            ],
        )
        self.assertIsNotNone(obj)

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = CustomerInstrumentResponse()

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = CustomerInstrumentResponse(
            id=8234,
        )
        d = obj.to_dict()
        self.assertIsInstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = CustomerInstrumentResponse()
        d = obj.to_dict()
        self.assertNotIn("id", d)
        self.assertNotIn("barcode", d)
        self.assertNotIn("companyName", d)
        self.assertNotIn("instrumentName", d)
        self.assertNotIn("instrumentCategory", d)
        self.assertNotIn("itemName", d)
        self.assertNotIn("make", d)
        self.assertNotIn("model", d)
        self.assertNotIn("range", d)
        self.assertNotIn("type", d)
        self.assertNotIn("tolerance", d)
        self.assertNotIn("serialNo", d)
        self.assertNotIn("tagNo", d)
        self.assertNotIn("controlNo", d)
        self.assertNotIn("calibrationFrequency", d)
        self.assertNotIn("workspaceCode", d)
        self.assertNotIn("calibrationFrequencySpan", d)
        self.assertNotIn("calibratedDate", d)
        self.assertNotIn("dueDate", d)
        self.assertNotIn("active", d)
        self.assertNotIn("parentTagNo", d)
        self.assertNotIn("departmentName", d)
        self.assertNotIn("verificationDueDate", d)
        self.assertNotIn("calibrationCost", d)
        self.assertNotIn("isCalibratedExternally", d)
        self.assertNotIn("calibrationVendor", d)
        self.assertNotIn("remarks", d)
        self.assertNotIn("instrumentNotes", d)
        self.assertNotIn("isMobile", d)
        self.assertNotIn("isCalibrationRequired", d)
        self.assertNotIn("lastReceivedDate", d)
        self.assertNotIn("lastDeliveredDate", d)
        self.assertNotIn("calibrationStatus", d)
        self.assertNotIn("receivedCondition", d)
        self.assertNotIn("auditedDate", d)
        self.assertNotIn("certificateUrl", d)
        self.assertNotIn("projectNames", d)

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {}
        obj = CustomerInstrumentResponse.from_dict(data)
        self.assertIsNotNone(obj)

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        self.assertIsNone(CustomerInstrumentResponse.from_dict(None))

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = CustomerInstrumentResponse(
            id=8234,
        )
        json_str = obj.to_json()
        restored = CustomerInstrumentResponse.from_json(json_str)
        self.assertIsNotNone(restored)

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_enum_calibration_frequency_span_invalid_value_raises(self):
        """Test invalid enum value for calibration_frequency_span raises ValidationError."""
        with self.assertRaises(ValidationError):
            CustomerInstrumentResponse(
                calibration_frequency_span="INVALID_ENUM_VALUE_XYZ",
            )


if __name__ == "__main__":
    unittest.main()
