# coding: utf-8

"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.authentication_request import AuthenticationRequest

class TestAuthenticationRequest(unittest.TestCase):
    """AuthenticationRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AuthenticationRequest:
        """Test AuthenticationRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AuthenticationRequest`
        """
        model = AuthenticationRequest()
        if include_optional:
            return AuthenticationRequest(
                access_key = 'mqt_live_7xK2pL9nR4tW8yF3',
                secret_key = 'sk_mqt_5hJ8mD2vB6nQ9xK4'
            )
        else:
            return AuthenticationRequest(
                access_key = 'mqt_live_7xK2pL9nR4tW8yF3',
                secret_key = 'sk_mqt_5hJ8mD2vB6nQ9xK4',
        )
        """

    def testAuthenticationRequest(self):
        """Test AuthenticationRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
