# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_response import CustomerResponse


class TestCustomerResponse(unittest.TestCase):
    """CustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerResponse:
        """Test CustomerResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `CustomerResponse`
        """
        model = CustomerResponse()
        if include_optional:
            return CustomerResponse(
                id = 10427,
                parent_company_code = 'M3-HQ',
                company_code = 'MCS-001',
                is_inactive = False,
                company_name = 'Metquay Inc.',
                email = 'accounts@metquay.com',
                website = 'https://www.metquay.com',
                payment_method = 'Bank Transfer',
                phone = '+1-312-555-0123',
                mobile = '+1-312-555-0124',
                fax = '+1-312-555-0125',
                other = '+1-312-555-0126',
                activate_alerts = True,
                workspace_code = 'NA-HQ',
                has_billing_address = True,
                billing_addr1 = '123 Innovation Drive',
                billing_addr2 = 'Suite 400',
                billing_city = 'Chicago',
                billing_state = 'Illinois',
                billing_zip = '60606-1234',
                billing_country = 'United States',
                billing_phone1 = '+1-312-555-0130',
                billing_phone2 = '+1-312-555-0131',
                has_shipping_address = True,
                shipping_addr1 = '456 Distribution Parkway',
                shipping_addr2 = 'Building B, Dock 7',
                shipping_city = 'Elk Grove Village',
                shipping_state = 'Illinois',
                shipping_zip = '60007-2345',
                shipping_country = 'United States',
                customer_specific_requirements = 'All deliveries require forklift access and must be scheduled 24 hours in advance. Contact warehouse manager at ext. 4500.',
                notes = 'Premium support customer since 2018. Monthly calibration volume averages 50-75 instruments. Primary contact: John Smith (john.smith@metquay.com)',
                short_name = 'Metquay',
                is_taxable = True,
                tax_code = 'TAX-EXEMPT-IL-2024',
                opening_balance = 12500.75
            )
        else:
            return CustomerResponse(
        )
        """

    def testCustomerResponse(self):
        """Test CustomerResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
