"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from pydantic import ValidationError

from openapi_client.models.customer_request import CustomerRequest


class TestCustomerRequest(unittest.TestCase):
    """CustomerRequest unit tests"""

    _REQUIRED_KWARGS = {
        "company_name": "Metquay Inc.",
    }

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #
    def test_construction_required_only(self):
        """Test constructing CustomerRequest with only required fields."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        self.assertEqual(obj.company_name, "Metquay Inc.")

    def test_full_construction(self):
        """Test constructing CustomerRequest with all non-date fields."""
        obj = CustomerRequest(
            parent_company_code="M3-HQ",
            company_code="MCS-001",
            is_inactive=False,
            company_name="Metquay Inc.",
            email="accounts@metquay.com",
            website="https://www.metquay.com",
            payment_method="Bank Transfer",
            phone="+1-312-555-0123",
            mobile="+1-312-555-0124",
            fax="+1-312-555-0125",
            other="+1-312-555-0126",
            activate_alerts=True,
            workspace_code="NA-HQ",
            has_billing_address=True,
            billing_addr1="123 Innovation Drive",
            billing_addr2="Suite 400",
            billing_city="Chicago",
            billing_state="Illinois",
            billing_zip="60606-1234",
            billing_country="United States",
            billing_phone1="+1-312-555-0130",
            billing_phone2="+1-312-555-0131",
            has_shipping_address=True,
            shipping_addr1="456 Distribution Parkway",
            shipping_addr2="Building B, Dock 7",
            shipping_city="Elk Grove Village",
            shipping_state="Illinois",
            shipping_zip="60007-2345",
            shipping_country="United States",
            customer_specific_requirements="All deliveries require forklift access and must be scheduled 24 hours in advance. Contact warehouse manager at ext. 4500.",
            notes="Premium support customer since 2018. Monthly calibration volume averages 50-75 instruments. Primary contact: John Smith (john.smith@metquay.com)",
            short_name="Metquay",
            is_taxable=True,
            tax_code="TAX-EXEMPT-IL-2024",
            opening_balance=12500.75,
        )
        self.assertIsNotNone(obj)

    def test_optional_fields_default_to_none(self):
        """Test that optional fields without defaults are None."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        self.assertIsNone(obj.parent_company_code)
        self.assertIsNone(obj.company_code)
        self.assertIsNone(obj.email)
        self.assertIsNone(obj.website)
        self.assertIsNone(obj.payment_method)
        self.assertIsNone(obj.phone)
        self.assertIsNone(obj.mobile)
        self.assertIsNone(obj.fax)
        self.assertIsNone(obj.other)
        self.assertIsNone(obj.workspace_code)
        self.assertIsNone(obj.billing_addr1)
        self.assertIsNone(obj.billing_addr2)
        self.assertIsNone(obj.billing_city)
        self.assertIsNone(obj.billing_state)
        self.assertIsNone(obj.billing_zip)
        self.assertIsNone(obj.billing_country)
        self.assertIsNone(obj.billing_phone1)
        self.assertIsNone(obj.billing_phone2)
        self.assertIsNone(obj.shipping_addr1)
        self.assertIsNone(obj.shipping_addr2)
        self.assertIsNone(obj.shipping_city)
        self.assertIsNone(obj.shipping_state)
        self.assertIsNone(obj.shipping_zip)
        self.assertIsNone(obj.shipping_country)
        self.assertIsNone(obj.customer_specific_requirements)
        self.assertIsNone(obj.notes)
        self.assertIsNone(obj.short_name)
        self.assertIsNone(obj.tax_code)
        self.assertIsNone(obj.opening_balance)

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        self.assertEqual(obj.is_inactive, False)
        self.assertEqual(obj.activate_alerts, False)
        self.assertEqual(obj.has_billing_address, False)
        self.assertEqual(obj.has_shipping_address, False)
        self.assertEqual(obj.is_taxable, True)

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        self.assertIsInstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        self.assertNotIn("parentCompanyCode", d)
        self.assertNotIn("companyCode", d)
        self.assertNotIn("email", d)
        self.assertNotIn("website", d)
        self.assertNotIn("paymentMethod", d)
        self.assertNotIn("phone", d)
        self.assertNotIn("mobile", d)
        self.assertNotIn("fax", d)
        self.assertNotIn("other", d)
        self.assertNotIn("workspaceCode", d)
        self.assertNotIn("billingAddr1", d)
        self.assertNotIn("billingAddr2", d)
        self.assertNotIn("billingCity", d)
        self.assertNotIn("billingState", d)
        self.assertNotIn("billingZip", d)
        self.assertNotIn("billingCountry", d)
        self.assertNotIn("billingPhone1", d)
        self.assertNotIn("billingPhone2", d)
        self.assertNotIn("shippingAddr1", d)
        self.assertNotIn("shippingAddr2", d)
        self.assertNotIn("shippingCity", d)
        self.assertNotIn("shippingState", d)
        self.assertNotIn("shippingZip", d)
        self.assertNotIn("shippingCountry", d)
        self.assertNotIn("customerSpecificRequirements", d)
        self.assertNotIn("notes", d)
        self.assertNotIn("shortName", d)
        self.assertNotIn("taxCode", d)
        self.assertNotIn("openingBalance", d)

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
            "companyName": "Metquay Inc.",
        }
        obj = CustomerRequest.from_dict(data)
        self.assertIsNotNone(obj)
        self.assertEqual(obj.company_name, "Metquay Inc.")

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        self.assertIsNone(CustomerRequest.from_dict(None))

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = CustomerRequest(**self._REQUIRED_KWARGS)
        json_str = obj.to_json()
        restored = CustomerRequest.from_json(json_str)
        self.assertIsNotNone(restored)

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_missing_company_name_raises(self):
        """Test that missing required 'company_name' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "company_name"}
        with self.assertRaises(ValidationError):
            CustomerRequest(**kwargs)


if __name__ == "__main__":
    unittest.main()
