"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest

from pydantic import ValidationError

from openapi_client.models.customer_instrument_request import CustomerInstrumentRequest


class TestCustomerInstrumentRequest(unittest.TestCase):
    """CustomerInstrumentRequest unit tests"""

    _REQUIRED_KWARGS = {
        "name": "Fluke 87V Industrial Digital Multimeter",
        "company_id": "MCS-001",
        "instrument_category_name": "Digital Multimeter",
    }

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #
    def test_construction_required_only(self):
        """Test constructing CustomerInstrumentRequest with only required fields."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)
        self.assertEqual(obj.name, "Fluke 87V Industrial Digital Multimeter")
        self.assertEqual(obj.company_id, "MCS-001")
        self.assertEqual(obj.instrument_category_name, "Digital Multimeter")

    def test_full_construction(self):
        """Test constructing CustomerInstrumentRequest with all non-date fields."""
        obj = CustomerInstrumentRequest(
            name="Fluke 87V Industrial Digital Multimeter",
            company_id="MCS-001",
            serial_no="FLK-87V-2024-4582",
            tag_no="METER-LAB-87V-042",
            make="Fluke Corporation",
            model="87V Max",
            range="0-1000V DC, 0-750V AC, 0-10A, 0-50MΩ",
            instrument_category_name="Digital Multimeter",
            calibration_frequency="180",
            calibration_frequency_span="DAY",
            instrument_status="RECEIVED",
            workspace_code="NA-HQ",
        )
        self.assertIsNotNone(obj)

    def test_optional_fields_default_to_none(self):
        """Test that optional fields without defaults are None."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)
        self.assertIsNone(obj.serial_no)
        self.assertIsNone(obj.tag_no)
        self.assertIsNone(obj.make)
        self.assertIsNone(obj.model)
        self.assertIsNone(obj.range)
        self.assertIsNone(obj.calibration_frequency)
        self.assertIsNone(obj.calibration_frequency_span)
        self.assertIsNone(obj.instrument_status)
        self.assertIsNone(obj.workspace_code)

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        self.assertIsInstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        self.assertNotIn("serialNo", d)
        self.assertNotIn("tagNo", d)
        self.assertNotIn("make", d)
        self.assertNotIn("model", d)
        self.assertNotIn("range", d)
        self.assertNotIn("calibrationFrequency", d)
        self.assertNotIn("calibrationFrequencySpan", d)
        self.assertNotIn("instrumentStatus", d)
        self.assertNotIn("lastReceivedDate", d)
        self.assertNotIn("lastDeliveredDate", d)
        self.assertNotIn("workspaceCode", d)

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
            "name": "Fluke 87V Industrial Digital Multimeter",
            "companyId": "MCS-001",
            "instrumentCategoryName": "Digital Multimeter",
        }
        obj = CustomerInstrumentRequest.from_dict(data)
        self.assertIsNotNone(obj)
        self.assertEqual(obj.name, "Fluke 87V Industrial Digital Multimeter")
        self.assertEqual(obj.company_id, "MCS-001")
        self.assertEqual(obj.instrument_category_name, "Digital Multimeter")

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        self.assertIsNone(CustomerInstrumentRequest.from_dict(None))

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = CustomerInstrumentRequest(**self._REQUIRED_KWARGS)
        json_str = obj.to_json()
        restored = CustomerInstrumentRequest.from_json(json_str)
        self.assertIsNotNone(restored)

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_missing_name_raises(self):
        """Test that missing required 'name' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "name"}
        with self.assertRaises(ValidationError):
            CustomerInstrumentRequest(**kwargs)

    def test_missing_company_id_raises(self):
        """Test that missing required 'company_id' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "company_id"}
        with self.assertRaises(ValidationError):
            CustomerInstrumentRequest(**kwargs)

    def test_missing_instrument_category_name_raises(self):
        """Test that missing required 'instrument_category_name' raises ValidationError."""
        kwargs = {
            k: v
            for k, v in self._REQUIRED_KWARGS.items()
            if k != "instrument_category_name"
        }
        with self.assertRaises(ValidationError):
            CustomerInstrumentRequest(**kwargs)

    def test_enum_calibration_frequency_span_invalid_value_raises(self):
        """Test invalid enum value for calibration_frequency_span raises ValidationError."""
        with self.assertRaises(ValidationError):
            CustomerInstrumentRequest(
                calibration_frequency_span="INVALID_ENUM_VALUE_XYZ",
            )


if __name__ == "__main__":
    unittest.main()
