"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import pytest
from pydantic import ValidationError

from openapi_client.models.work_request import WorkRequest


class TestWorkRequest:
    """WorkRequest unit tests"""

    _REQUIRED_KWARGS = {
        "customer_instrument_id": 8234,
    }

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #
    def test_construction_required_only(self):
        """Test constructing WorkRequest with only required fields."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        assert obj.customer_instrument_id == 8234


    def test_full_construction(self):
        """Test constructing WorkRequest with all non-date fields."""
        obj = WorkRequest(
            customer_instrument_id=8234,
            accreditation=True,
            compliance_required=True,
            site_job=False,
            outsource=False,
            customer_specific_requirements='Calibration required at 5 specific points: -20°C, 0°C, 25°C, 50°C, 80°C. Certificate must include measurement uncertainty at 95% confidence level.',
            scope='Full calibration per manufacturer specifications. 5-point verification across all ranges. Includes NIST traceable certificate.',
            certificate_address='Metquay Inc., 123 Innovation Drive, Suite 400, Chicago, IL 60606-1234, United States',
            remarks='Rush order requested by customer. Standard 5-day turnaround reduced to 3 days. Quote #Q-2024-0123 approved.',
            work_flow_type='Calibration',
            sales_order_no='SO-2024-04567',
            workspace_code='NA-HQ',
            sub_con_details='High-voltage calibration subcontracted to PowerCal Labs. Expected return date: 01-26-2024. Subcontractor PO #PO-2024-8910.',
        )
        assert obj is not None

    def test_optional_fields_default_to_none(self):
        """Test that optional fields without defaults are None."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        assert obj.customer_specific_requirements is None
        assert obj.scope is None
        assert obj.certificate_address is None
        assert obj.remarks is None
        assert obj.sales_order_no is None
        assert obj.workspace_code is None
        assert obj.sub_con_details is None

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        assert obj.accreditation == False
        assert obj.compliance_required == False
        assert obj.site_job == False
        assert obj.outsource == False
        assert obj.work_flow_type == 'Calibration'

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        assert isinstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        assert "inDate" not in d
        assert "customerSpecificRequirements" not in d
        assert "scope" not in d
        assert "certificateAddress" not in d
        assert "remarks" not in d
        assert "deliveryDate" not in d
        assert "salesOrderNo" not in d
        assert "workspaceCode" not in d
        assert "subConDetails" not in d

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
            "customerInstrumentId": 8234,
        }
        obj = WorkRequest.from_dict(data)
        assert obj is not None
        assert obj.customer_instrument_id == 8234

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        assert WorkRequest.from_dict(None) is None

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = WorkRequest(**self._REQUIRED_KWARGS)
        json_str = obj.to_json()
        restored = WorkRequest.from_json(json_str)
        assert restored is not None

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_missing_customer_instrument_id_raises(self):
        """Test that missing required 'customer_instrument_id' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "customer_instrument_id"}
        with pytest.raises(ValidationError):
            WorkRequest(**kwargs)

    def test_enum_work_flow_type_invalid_value_raises(self):
        """Test invalid enum value for work_flow_type raises ValidationError."""
        with pytest.raises(ValidationError):
            WorkRequest(
                work_flow_type="INVALID_ENUM_VALUE_XYZ",
            )

