# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.work_response import WorkResponse


class TestWorkResponse(unittest.TestCase):
    """WorkResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkResponse:
        """Test WorkResponse
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkResponse`
        """
        model = WorkResponse()
        if include_optional:
            return WorkResponse(
                id = 21568,
                work_no = 'CAL-2024-021568',
                customer_instrument_id = 8234,
                in_date = 'Sat Apr 14 18:00:00 CST 8',
                accreditation = True,
                compliance_required = True,
                site_job = False,
                outsource = False,
                customer_specific_requirements = 'Calibration required at 5 specific points: -20°C, 0°C, 25°C, 50°C, 80°C. Certificate must include measurement uncertainty at 95% confidence level.',
                scope = 'Full calibration per manufacturer specifications. 5-point verification across all ranges. Includes NIST traceable certificate.',
                certificate_address = 'Metquay Inc., 123 Innovation Drive, Suite 400, Chicago, IL 60606-1234, United States',
                remarks = 'Rush order requested by customer. Standard 5-day turnaround reduced to 3 days. Quote #Q-2024-0123 approved.',
                work_flow_type = 'Calibration',
                delivery_date = 'Mon Nov 12 18:00:00 CST 8',
                sales_order_no = 'SO-2024-04567',
                workspace_code = 'NA-HQ',
                sub_con_details = 'High-voltage calibration subcontracted to PowerCal Labs. Returned on 01-26-2024. Subcontractor PO #PO-2024-8910.',
                customer = 'Metquay Inc.',
                instrument_name = 'Fluke 87V Industrial Digital Multimeter',
                instrument_serial_no = 'FLK-87V-2024-4582',
                instrument_tag_no = 'METER-LAB-87V-042',
                instrument_barcode = 'MQ-87V-2024-04582',
                instrument_category_name = 'Digital Multimeter',
                item_description = 'Fluke 87V Max Digital Multimeter with NIST certification',
                department_name = 'Metrology Lab - Electrical',
                status = 'Finished',
                report_type = 'Certificate',
                accreditation_type = 'Accredited',
                procedure = 'FLUKE-87V-CAL-PROC-Rev4',
                technician = 'Sandeep Nair',
                work_date = 'Sat Apr 14 18:00:00 CST 8',
                due_date = 'Mon Nov 12 18:00:00 CST 8',
                revision_no = 1,
                certificate_no = 'MQ-CAL-2024-021568',
                finished_date = 'Wed Aug 15 18:00:00 CST 8',
                finished_by = 'Sandeep Nair',
                sales_person = 'Michael Chen',
                recommended_due_date = 'Tue Feb 13 18:00:00 CST 14',
                calibrated_date = 'Wed Aug 15 18:00:00 CST 8',
                work_start_date = 'Sat Apr 14 18:00:00 CST 8',
                customer_po_no = 'PO-2024-01234',
                so_description = 'Rush calibration service - Fluke 87V Multimeter',
                workspace = 'NA-HQ Electrical Lab',
                job_type = 'At Lab'
            )
        else:
            return WorkResponse(
        )
        """

    def testWorkResponse(self):
        """Test WorkResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
