"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from unittest.mock import MagicMock

from openapi_client.api_client import ApiClient

from openapi_client.api.customers_api import CustomersApi


class TestCustomersApi:
    """CustomersApi unit tests"""

    def setup_method(self):
        """Set up test fixtures before each test method."""
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = CustomersApi(api_client=self.api_client)

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self):
        """CustomersApi can be created with a mock ApiClient."""
        assert isinstance(self.api, CustomersApi)
        assert self.api.api_client is self.api_client

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_create_customer(self):
        assert callable(getattr(self.api, "create_customer", None))

    def test_has_delete_customer(self):
        assert callable(getattr(self.api, "delete_customer", None))

    def test_has_get_customers(self):
        assert callable(getattr(self.api, "get_customers", None))

    def test_has_update_customer(self):
        assert callable(getattr(self.api, "update_customer", None))


    def test_has_with_http_info_variants(self):
        for method in (
            "create_customer_with_http_info",
            "delete_customer_with_http_info",
            "get_customers_with_http_info",
            "update_customer_with_http_info",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    def test_has_without_preload_content_variants(self):
        for method in (
            "create_customer_without_preload_content",
            "delete_customer_without_preload_content",
            "get_customers_without_preload_content",
            "update_customer_without_preload_content",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    # ------------------------------------------------------------------ #
    #  _create_customer_serialize
    # ------------------------------------------------------------------ #
    def _call_create_customer_serialize(self, **overrides):
        """Helper to call _create_customer_serialize with defaults."""
        defaults = {
            "customer_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._create_customer_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_create_customer_serialize_method_and_path(self):
        """_create_customer_serialize uses POST /customers."""
        kw = self._call_create_customer_serialize()
        assert kw["method"] == "POST"
        assert kw["resource_path"] == "/customers"

    def test_create_customer_serialize_bearer_auth(self):
        """_create_customer_serialize requires bearerAuth."""
        kw = self._call_create_customer_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_create_customer_serialize_body(self):
        """_create_customer_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_create_customer_serialize(customer_request=mock_body)
        assert kw["body"] is mock_body

    def test_create_customer_serialize_no_path_params(self):
        """_create_customer_serialize has no path parameters."""
        kw = self._call_create_customer_serialize()
        assert kw["path_params"] == {}

    def test_create_customer_serialize_no_query_params(self):
        """_create_customer_serialize has no query parameters."""
        kw = self._call_create_customer_serialize()
        assert kw["query_params"] == []

    # ------------------------------------------------------------------ #
    #  _delete_customer_serialize
    # ------------------------------------------------------------------ #
    def _call_delete_customer_serialize(self, **overrides):
        """Helper to call _delete_customer_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._delete_customer_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_delete_customer_serialize_method_and_path(self):
        """_delete_customer_serialize uses DELETE /customers/{metquayId}."""
        kw = self._call_delete_customer_serialize()
        assert kw["method"] == "DELETE"
        assert kw["resource_path"] == "/customers/{metquayId}"

    def test_delete_customer_serialize_bearer_auth(self):
        """_delete_customer_serialize requires bearerAuth."""
        kw = self._call_delete_customer_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_delete_customer_serialize_no_body(self):
        """_delete_customer_serialize sends no body."""
        kw = self._call_delete_customer_serialize()
        assert kw["body"] is None

    def test_delete_customer_serialize_path_params(self):
        """_delete_customer_serialize passes path parameters."""
        kw = self._call_delete_customer_serialize(
            metquay_id=99,
        )
        assert kw["path_params"] == {
            "metquayId": 99,
        }

    def test_delete_customer_serialize_no_query_params(self):
        """_delete_customer_serialize has no query parameters."""
        kw = self._call_delete_customer_serialize()
        assert kw["query_params"] == []

    # ------------------------------------------------------------------ #
    #  _get_customers_serialize
    # ------------------------------------------------------------------ #
    def _call_get_customers_serialize(self, **overrides):
        """Helper to call _get_customers_serialize with defaults."""
        defaults = {
            "workspace_code": None,
            "first": None,
            "limit": None,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._get_customers_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_get_customers_serialize_method_and_path(self):
        """_get_customers_serialize uses GET /customers."""
        kw = self._call_get_customers_serialize()
        assert kw["method"] == "GET"
        assert kw["resource_path"] == "/customers"

    def test_get_customers_serialize_bearer_auth(self):
        """_get_customers_serialize requires bearerAuth."""
        kw = self._call_get_customers_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_get_customers_serialize_no_body(self):
        """_get_customers_serialize sends no body."""
        kw = self._call_get_customers_serialize()
        assert kw["body"] is None

    def test_get_customers_serialize_no_path_params(self):
        """_get_customers_serialize has no path parameters."""
        kw = self._call_get_customers_serialize()
        assert kw["path_params"] == {}

    def test_get_customers_serialize_no_query_when_none(self):
        """Omits query params when all are None."""
        kw = self._call_get_customers_serialize()
        assert kw["query_params"] == []

    def test_get_customers_serialize_workspace_code(self):
        """Includes workspaceCode query param."""
        kw = self._call_get_customers_serialize(workspace_code="test_value")
        assert ("workspaceCode", "test_value") in kw["query_params"]

    def test_get_customers_serialize_first(self):
        """Includes first query param."""
        kw = self._call_get_customers_serialize(first=10)
        assert ("first", 10) in kw["query_params"]

    def test_get_customers_serialize_limit(self):
        """Includes limit query param."""
        kw = self._call_get_customers_serialize(limit=10)
        assert ("limit", 10) in kw["query_params"]


    # ------------------------------------------------------------------ #
    #  _update_customer_serialize
    # ------------------------------------------------------------------ #
    def _call_update_customer_serialize(self, **overrides):
        """Helper to call _update_customer_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "customer_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._update_customer_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_update_customer_serialize_method_and_path(self):
        """_update_customer_serialize uses PUT /customers/{metquayId}."""
        kw = self._call_update_customer_serialize()
        assert kw["method"] == "PUT"
        assert kw["resource_path"] == "/customers/{metquayId}"

    def test_update_customer_serialize_bearer_auth(self):
        """_update_customer_serialize requires bearerAuth."""
        kw = self._call_update_customer_serialize()
        assert kw["auth_settings"] == ["bearerAuth"]

    def test_update_customer_serialize_body(self):
        """_update_customer_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_update_customer_serialize(customer_request=mock_body)
        assert kw["body"] is mock_body

    def test_update_customer_serialize_path_params(self):
        """_update_customer_serialize passes path parameters."""
        kw = self._call_update_customer_serialize(
            metquay_id=99,
        )
        assert kw["path_params"] == {
            "metquayId": 99,
        }

    def test_update_customer_serialize_no_query_params(self):
        """_update_customer_serialize has no query parameters."""
        kw = self._call_update_customer_serialize()
        assert kw["query_params"] == []

