"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from unittest.mock import MagicMock

from openapi_client.api_client import ApiClient

from openapi_client.api.authenticate_api import AuthenticateApi


class TestAuthenticateApi:
    """AuthenticateApi unit tests"""

    def setup_method(self):
        """Set up test fixtures before each test method."""
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = AuthenticateApi(api_client=self.api_client)

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self):
        """AuthenticateApi can be created with a mock ApiClient."""
        assert isinstance(self.api, AuthenticateApi)
        assert self.api.api_client is self.api_client

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_get_access_token(self):
        assert callable(getattr(self.api, "get_access_token", None))


    def test_has_with_http_info_variants(self):
        for method in (
            "get_access_token_with_http_info",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    def test_has_without_preload_content_variants(self):
        for method in (
            "get_access_token_without_preload_content",
        ):
            assert callable(getattr(self.api, method, None)), f"{method} should exist"

    # ------------------------------------------------------------------ #
    #  _get_access_token_serialize
    # ------------------------------------------------------------------ #
    def _call_get_access_token_serialize(self, **overrides):
        """Helper to call _get_access_token_serialize with defaults."""
        defaults = {
            "authentication_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._get_access_token_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_get_access_token_serialize_method_and_path(self):
        """_get_access_token_serialize uses POST /authenticate."""
        kw = self._call_get_access_token_serialize()
        assert kw["method"] == "POST"
        assert kw["resource_path"] == "/authenticate"

    def test_get_access_token_serialize_no_auth(self):
        """_get_access_token_serialize uses no auth."""
        kw = self._call_get_access_token_serialize()
        assert kw["auth_settings"] == []

    def test_get_access_token_serialize_body(self):
        """_get_access_token_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_get_access_token_serialize(authentication_request=mock_body)
        assert kw["body"] is mock_body

    def test_get_access_token_serialize_no_path_params(self):
        """_get_access_token_serialize has no path parameters."""
        kw = self._call_get_access_token_serialize()
        assert kw["path_params"] == {}

    def test_get_access_token_serialize_no_query_params(self):
        """_get_access_token_serialize has no query parameters."""
        kw = self._call_get_access_token_serialize()
        assert kw["query_params"] == []

