# coding: utf-8

"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.customer_instrument_response import CustomerInstrumentResponse

class TestCustomerInstrumentResponse(unittest.TestCase):
    """CustomerInstrumentResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CustomerInstrumentResponse:
        """Test CustomerInstrumentResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CustomerInstrumentResponse`
        """
        model = CustomerInstrumentResponse()
        if include_optional:
            return CustomerInstrumentResponse(
                id = 8234,
                barcode = 'MQ-87V-2024-04582',
                company_name = 'Metquay Inc.',
                instrument_name = 'Fluke 87V Industrial Digital Multimeter',
                instrument_category = 'Digital Multimeter',
                item_name = 'Fluke 87V Digital Multimeter',
                make = 'Fluke Corporation',
                model = '87V Max',
                range = '0-1000V DC, 0-750V AC, 0-10A, 0-50MΩ',
                type = 'True RMS Digital Multimeter',
                tolerance = '±0.05% basic DC accuracy',
                serial_no = 'FLK-87V-2024-4582',
                tag_no = 'METER-LAB-87V-042',
                control_no = 'CTL-2024-042',
                calibration_frequency = '180',
                workspace_code = 'NA-HQ',
                calibration_frequency_span = 'DAY',
                calibrated_date = 'Sat Apr 14 18:00:00 CST 8',
                due_date = 'Tue Feb 13 18:00:00 CST 14',
                active = True,
                parent_tag_no = 'SYSTEM-87V-MAIN-001',
                department_name = 'Metrology Lab - Electrical',
                verification_due_date = 'Wed Sep 13 18:00:00 CST 13',
                calibration_cost = 185.5,
                is_calibrated_externally = False,
                calibration_vendor = 'Metquay Calibration Services',
                remarks = 'High-precision instrument for ISO 17025 accredited calibrations. Requires special handling.',
                instrument_notes = 'Battery replaced on 12-15-2023. Firmware updated to v2.1. Next firmware check due: 06-2024.',
                is_mobile = True,
                is_calibration_required = True,
                last_received_date = 'Sat Apr 14 18:00:00 CST 8',
                last_delivered_date = 'Mon Feb 13 18:00:00 CST 8',
                calibration_status = 'Good',
                received_condition = 'Good',
                audited_date = 'Sat Apr 14 18:00:00 CST 8',
                certificate_url = 'https://certificates.metquay.com/FLK-87V-2024-4582-20240122.pdf',
                project_names = ["ISO-17025-2024-Upgrade","Lab-Certification-Q2","Customer-Project-Acme-001"]
            )
        else:
            return CustomerInstrumentResponse(
        )
        """

    def testCustomerInstrumentResponse(self):
        """Test CustomerInstrumentResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
