# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.work_request import WorkRequest


class TestWorkRequest(unittest.TestCase):
    """WorkRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> WorkRequest:
        """Test WorkRequest
        include_optional is a boolean, when False only required
        params are included, when True both required and
        optional params are included"""
        # uncomment below to create an instance of `WorkRequest`
        """
        model = WorkRequest()
        if include_optional:
            return WorkRequest(
                customer_instrument_id = 8234,
                in_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                accreditation = True,
                compliance_required = True,
                site_job = False,
                outsource = False,
                customer_specific_requirements = 'Calibration required at 5 specific points: -20°C, 0°C, 25°C, 50°C, 80°C. Certificate must include measurement uncertainty at 95% confidence level.',
                scope = 'Full calibration per manufacturer specifications. 5-point verification across all ranges. Includes NIST traceable certificate.',
                certificate_address = 'Metquay Inc., 123 Innovation Drive, Suite 400, Chicago, IL 60606-1234, United States',
                remarks = 'Rush order requested by customer. Standard 5-day turnaround reduced to 3 days. Quote #Q-2024-0123 approved.',
                work_flow_type = 'Calibration',
                delivery_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                sales_order_no = 'SO-2024-04567',
                workspace_code = 'NA-HQ',
                sub_con_details = 'High-voltage calibration subcontracted to PowerCal Labs. Expected return date: 01-26-2024. Subcontractor PO #PO-2024-8910.'
            )
        else:
            return WorkRequest(
                customer_instrument_id = 8234,
        )
        """

    def testWorkRequest(self):
        """Test WorkRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == "__main__":
    unittest.main()
