"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from openapi_client.models.customer_response import CustomerResponse


class TestCustomerResponse:
    """CustomerResponse unit tests"""

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #

    def test_construction_empty(self):
        """Test constructing CustomerResponse with no arguments (all optional)."""
        obj = CustomerResponse()
        assert obj is not None

    def test_full_construction(self):
        """Test constructing CustomerResponse with all non-date fields."""
        obj = CustomerResponse(
            id=10427,
            parent_company_code="M3-HQ",
            company_code="MCS-001",
            is_inactive=False,
            company_name="Metquay Inc.",
            email="accounts@metquay.com",
            website="https://www.metquay.com",
            payment_method="Bank Transfer",
            phone="+1-312-555-0123",
            mobile="+1-312-555-0124",
            fax="+1-312-555-0125",
            other="+1-312-555-0126",
            activate_alerts=True,
            workspace_code="NA-HQ",
            has_billing_address=True,
            billing_addr1="123 Innovation Drive",
            billing_addr2="Suite 400",
            billing_city="Chicago",
            billing_state="Illinois",
            billing_zip="60606-1234",
            billing_country="United States",
            billing_phone1="+1-312-555-0130",
            billing_phone2="+1-312-555-0131",
            has_shipping_address=True,
            shipping_addr1="456 Distribution Parkway",
            shipping_addr2="Building B, Dock 7",
            shipping_city="Elk Grove Village",
            shipping_state="Illinois",
            shipping_zip="60007-2345",
            shipping_country="United States",
            customer_specific_requirements="All deliveries require forklift access and must be scheduled 24 hours in advance. Contact warehouse manager at ext. 4500.",
            notes="Premium support customer since 2018. Monthly calibration volume averages 50-75 instruments. Primary contact: John Smith (john.smith@metquay.com)",
            short_name="Metquay",
            is_taxable=True,
            tax_code="TAX-EXEMPT-IL-2024",
            opening_balance=12500.75,
        )
        assert obj is not None

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = CustomerResponse()

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = CustomerResponse(
            id=10427,
        )
        d = obj.to_dict()
        assert isinstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = CustomerResponse()
        d = obj.to_dict()
        assert "id" not in d
        assert "parentCompanyCode" not in d
        assert "companyCode" not in d
        assert "isInactive" not in d
        assert "companyName" not in d
        assert "email" not in d
        assert "website" not in d
        assert "paymentMethod" not in d
        assert "phone" not in d
        assert "mobile" not in d
        assert "fax" not in d
        assert "other" not in d
        assert "activateAlerts" not in d
        assert "workspaceCode" not in d
        assert "hasBillingAddress" not in d
        assert "billingAddr1" not in d
        assert "billingAddr2" not in d
        assert "billingCity" not in d
        assert "billingState" not in d
        assert "billingZip" not in d
        assert "billingCountry" not in d
        assert "billingPhone1" not in d
        assert "billingPhone2" not in d
        assert "hasShippingAddress" not in d
        assert "shippingAddr1" not in d
        assert "shippingAddr2" not in d
        assert "shippingCity" not in d
        assert "shippingState" not in d
        assert "shippingZip" not in d
        assert "shippingCountry" not in d
        assert "customerSpecificRequirements" not in d
        assert "notes" not in d
        assert "shortName" not in d
        assert "isTaxable" not in d
        assert "taxCode" not in d
        assert "openingBalance" not in d

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {}
        obj = CustomerResponse.from_dict(data)
        assert obj is not None

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        assert CustomerResponse.from_dict(None) is None

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = CustomerResponse(
            id=10427,
        )
        json_str = obj.to_json()
        restored = CustomerResponse.from_json(json_str)
        assert restored is not None

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
