"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import unittest
from unittest.mock import MagicMock

from openapi_client.api_client import ApiClient

from openapi_client.api.instrumentcategories_api import InstrumentcategoriesApi


class TestInstrumentcategoriesApi(unittest.TestCase):
    """InstrumentcategoriesApi unit tests"""

    def setUp(self) -> None:
        self.api_client = MagicMock(spec=ApiClient)
        self.api_client.select_header_accept.return_value = "application/json"
        self.api_client.select_header_content_type.return_value = "application/json"
        self.api = InstrumentcategoriesApi(api_client=self.api_client)

    def tearDown(self) -> None:
        pass

    # ------------------------------------------------------------------ #
    #  Instantiation
    # ------------------------------------------------------------------ #
    def test_instantiation_with_mock_client(self) -> None:
        """InstrumentcategoriesApi can be created with a mock ApiClient."""
        self.assertIsInstance(self.api, InstrumentcategoriesApi)
        self.assertIs(self.api.api_client, self.api_client)

    # ------------------------------------------------------------------ #
    #  Method existence
    # ------------------------------------------------------------------ #
    def test_has_create_instrument_category(self) -> None:
        self.assertTrue(callable(getattr(self.api, "create_instrument_category", None)))

    def test_has_delete_instrument_category(self) -> None:
        self.assertTrue(callable(getattr(self.api, "delete_instrument_category", None)))

    def test_has_update_instrument_category(self) -> None:
        self.assertTrue(callable(getattr(self.api, "update_instrument_category", None)))

    def test_has_with_http_info_variants(self) -> None:
        for method in (
            "create_instrument_category_with_http_info",
            "delete_instrument_category_with_http_info",
            "update_instrument_category_with_http_info",
        ):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    def test_has_without_preload_content_variants(self) -> None:
        for method in (
            "create_instrument_category_without_preload_content",
            "delete_instrument_category_without_preload_content",
            "update_instrument_category_without_preload_content",
        ):
            self.assertTrue(
                callable(getattr(self.api, method, None)),
                f"{method} should exist",
            )

    # ------------------------------------------------------------------ #
    #  _create_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_create_instrument_category_serialize(self, **overrides):
        """Helper to call _create_instrument_category_serialize with defaults."""
        defaults = {
            "instrument_category_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._create_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_create_instrument_category_serialize_method_and_path(self) -> None:
        """_create_instrument_category_serialize uses POST /instrument-categories."""
        kw = self._call_create_instrument_category_serialize()
        self.assertEqual(kw["method"], "POST")
        self.assertEqual(kw["resource_path"], "/instrument-categories")

    def test_create_instrument_category_serialize_bearer_auth(self) -> None:
        """_create_instrument_category_serialize requires bearerAuth."""
        kw = self._call_create_instrument_category_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_create_instrument_category_serialize_body(self) -> None:
        """_create_instrument_category_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_create_instrument_category_serialize(
            instrument_category_request=mock_body
        )
        self.assertIs(kw["body"], mock_body)

    def test_create_instrument_category_serialize_no_path_params(self) -> None:
        """_create_instrument_category_serialize has no path parameters."""
        kw = self._call_create_instrument_category_serialize()
        self.assertEqual(kw["path_params"], {})

    def test_create_instrument_category_serialize_no_query_params(self) -> None:
        """_create_instrument_category_serialize has no query parameters."""
        kw = self._call_create_instrument_category_serialize()
        self.assertEqual(kw["query_params"], [])

    # ------------------------------------------------------------------ #
    #  _delete_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_delete_instrument_category_serialize(self, **overrides):
        """Helper to call _delete_instrument_category_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._delete_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_delete_instrument_category_serialize_method_and_path(self) -> None:
        """_delete_instrument_category_serialize uses DELETE /instrument-categories/{metquayId}."""
        kw = self._call_delete_instrument_category_serialize()
        self.assertEqual(kw["method"], "DELETE")
        self.assertEqual(kw["resource_path"], "/instrument-categories/{metquayId}")

    def test_delete_instrument_category_serialize_bearer_auth(self) -> None:
        """_delete_instrument_category_serialize requires bearerAuth."""
        kw = self._call_delete_instrument_category_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_delete_instrument_category_serialize_no_body(self) -> None:
        """_delete_instrument_category_serialize sends no body."""
        kw = self._call_delete_instrument_category_serialize()
        self.assertIsNone(kw["body"])

    def test_delete_instrument_category_serialize_path_params(self) -> None:
        """_delete_instrument_category_serialize passes path parameters."""
        kw = self._call_delete_instrument_category_serialize(
            metquay_id=99,
        )
        self.assertEqual(
            kw["path_params"],
            {
                "metquayId": 99,
            },
        )

    def test_delete_instrument_category_serialize_no_query_params(self) -> None:
        """_delete_instrument_category_serialize has no query parameters."""
        kw = self._call_delete_instrument_category_serialize()
        self.assertEqual(kw["query_params"], [])

    # ------------------------------------------------------------------ #
    #  _update_instrument_category_serialize
    # ------------------------------------------------------------------ #
    def _call_update_instrument_category_serialize(self, **overrides):
        """Helper to call _update_instrument_category_serialize with defaults."""
        defaults = {
            "metquay_id": 42,
            "instrument_category_request": MagicMock(),
            "_request_auth": None,
            "_content_type": None,
            "_headers": None,
            "_host_index": 0,
        }
        defaults.update(overrides)
        self.api._update_instrument_category_serialize(**defaults)
        return self.api_client.param_serialize.call_args.kwargs

    def test_update_instrument_category_serialize_method_and_path(self) -> None:
        """_update_instrument_category_serialize uses PUT /instrument-categories/{metquayId}."""
        kw = self._call_update_instrument_category_serialize()
        self.assertEqual(kw["method"], "PUT")
        self.assertEqual(kw["resource_path"], "/instrument-categories/{metquayId}")

    def test_update_instrument_category_serialize_bearer_auth(self) -> None:
        """_update_instrument_category_serialize requires bearerAuth."""
        kw = self._call_update_instrument_category_serialize()
        self.assertEqual(kw["auth_settings"], ["bearerAuth"])

    def test_update_instrument_category_serialize_body(self) -> None:
        """_update_instrument_category_serialize forwards the request body."""
        mock_body = MagicMock()
        kw = self._call_update_instrument_category_serialize(
            instrument_category_request=mock_body
        )
        self.assertIs(kw["body"], mock_body)

    def test_update_instrument_category_serialize_path_params(self) -> None:
        """_update_instrument_category_serialize passes path parameters."""
        kw = self._call_update_instrument_category_serialize(
            metquay_id=99,
        )
        self.assertEqual(
            kw["path_params"],
            {
                "metquayId": 99,
            },
        )

    def test_update_instrument_category_serialize_no_query_params(self) -> None:
        """_update_instrument_category_serialize has no query parameters."""
        kw = self._call_update_instrument_category_serialize()
        self.assertEqual(kw["query_params"], [])


if __name__ == "__main__":
    unittest.main()
