"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import pytest
from pydantic import ValidationError

from openapi_client.models.authentication_response import AuthenticationResponse


class TestAuthenticationResponse:
    """AuthenticationResponse unit tests"""

    _REQUIRED_KWARGS = {
        "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzk5MjJ9.7H-bj0gF6cDxQqYqWlQqYqWlQqYqWlQqYqWlQqYqWlQqY",
        "token_type": "bearer",
    }

    # ------------------------------------------------------------------ #
    #  Construction
    # ------------------------------------------------------------------ #
    def test_construction_required_only(self):
        """Test constructing AuthenticationResponse with only required fields."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)
        assert (
            obj.access_token
            == "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzk5MjJ9.7H-bj0gF6cDxQqYqWlQqYqWlQqYqWlQqYqWlQqYqWlQqY"
        )
        assert obj.token_type == "bearer"

    def test_full_construction(self):
        """Test constructing AuthenticationResponse with all non-date fields."""
        obj = AuthenticationResponse(
            access_token="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzk5MjJ9.7H-bj0gF6cDxQqYqWlQqYqWlQqYqWlQqYqWlQqYqWlQqY",
            token_type="bearer",
            expires_in=900,
        )
        assert obj is not None

    def test_optional_fields_default_to_none(self):
        """Test that optional fields without defaults are None."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)
        assert obj.expires_in is None

    def test_defaults_are_correct(self):
        """Test that fields with explicit defaults are set correctly."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)

    # ------------------------------------------------------------------ #
    #  Serialization
    # ------------------------------------------------------------------ #
    def test_to_dict_uses_alias_keys(self):
        """Test that to_dict() produces camelCase alias keys."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        assert isinstance(d, dict)

    def test_to_dict_excludes_none(self):
        """Test that to_dict() excludes fields that are None."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)
        d = obj.to_dict()
        assert "expiresIn" not in d

    def test_from_dict_with_camel_case(self):
        """Test from_dict() accepts camelCase keys."""
        data = {
            "accessToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzk5MjJ9.7H-bj0gF6cDxQqYqWlQqYqWlQqYqWlQqYqWlQqYqWlQqY",
            "tokenType": "bearer",
        }
        obj = AuthenticationResponse.from_dict(data)
        assert obj is not None
        assert (
            obj.access_token
            == "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJleHAiOjE1MTYyMzk5MjJ9.7H-bj0gF6cDxQqYqWlQqYqWlQqYqWlQqYqWlQqYqWlQqY"
        )
        assert obj.token_type == "bearer"

    def test_from_dict_none_returns_none(self):
        """Test from_dict(None) returns None."""
        assert AuthenticationResponse.from_dict(None) is None

    def test_to_json_and_from_json_roundtrip(self):
        """Test JSON serialization roundtrip."""
        obj = AuthenticationResponse(**self._REQUIRED_KWARGS)
        json_str = obj.to_json()
        restored = AuthenticationResponse.from_json(json_str)
        assert restored is not None

    # ------------------------------------------------------------------ #
    #  Validation
    # ------------------------------------------------------------------ #
    def test_missing_access_token_raises(self):
        """Test that missing required 'access_token' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "access_token"}
        with pytest.raises(ValidationError):
            AuthenticationResponse(**kwargs)

    def test_missing_token_type_raises(self):
        """Test that missing required 'token_type' raises ValidationError."""
        kwargs = {k: v for k, v in self._REQUIRED_KWARGS.items() if k != "token_type"}
        with pytest.raises(ValidationError):
            AuthenticationResponse(**kwargs)
