#!/usr/bin/env python3
"""Generate read-only integration tests from the OpenAPI spec.

Reads ``1.0.json`` to discover GET-list endpoints, introspects
``pymetquay/client.py`` to find the corresponding ``list_*`` wrapper
methods, and writes:

  * ``tests/test_integration.py``   — high-level client integration tests
  * ``tests/test_response_shapes.py`` — raw-response-vs-model shape checks

Run after the openapi-generator step (called by ``generate.sh``).
"""

from __future__ import annotations

import ast
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SPEC_PATH = ROOT / "1.0.json"
CLIENT_PATH = ROOT / "pymetquay" / "client.py"
INTEGRATION_PATH = ROOT / "tests" / "test_integration.py"
SHAPES_PATH = ROOT / "tests" / "test_response_shapes.py"

_GENERATED = "AUTO-GENERATED by generate_integration_tests.py — DO NOT EDIT."


# ── Helpers ──────────────────────────────────────────────────────────────


def _snake(name: str) -> str:
    """``getCustomers`` → ``get_customers``."""
    return re.sub(r"(?<=[a-z0-9])([A-Z])", r"_\1", name).lower()


def _cls_to_mod(cls: str) -> str:
    """``CustomerResponse`` → ``customer_response``."""
    return re.sub(r"(?<!^)([A-Z])", r"_\1", cls).lower()


# ── Spec parsing ─────────────────────────────────────────────────────────


def _get_endpoints(spec: dict[str, object]) -> list[dict[str, object]]:
    """Return metadata for every GET operation in the spec."""
    endpoints: list[dict[str, object]] = []
    paths: dict[str, object] = spec.get("paths", {})  # type: ignore[assignment]
    for path, methods in paths.items():
        assert isinstance(methods, dict)
        op = methods.get("get")
        if op is None:
            continue
        assert isinstance(op, dict)
        tag = (op.get("tags") or [""])[0]
        schema = (
            op.get("responses", {})
            .get("200", {})
            .get("content", {})
            .get("application/json", {})
            .get("schema", {})
        )
        ref = (
            schema.get("items", {}).get("$ref", "")
            if schema.get("type") == "array"
            else schema.get("$ref", "")
        )
        endpoints.append(
            {
                "path": path,
                "operation_id": op["operationId"],
                "snake_id": _snake(str(op["operationId"])),
                "tag": tag,
                "response_model": ref.rsplit("/", 1)[-1] if ref else None,
            }
        )
    return endpoints


# ── Client introspection ─────────────────────────────────────────────────


def _list_methods(source: str) -> dict[str, dict[str, str]]:
    """Map generated method name → MetquayClient wrapper info.

    Returns e.g.::

        {"get_customers": {"wrapper": "list_customers",
                           "api_attr": "_customers_api"}}
    """
    tree = ast.parse(source)
    mapping: dict[str, dict[str, str]] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.FunctionDef) or not node.name.startswith("list_"):
            continue
        for child in ast.walk(node):
            if not isinstance(child, ast.Attribute):
                continue
            val = child.value
            if (
                isinstance(val, ast.Attribute)
                and isinstance(val.value, ast.Name)
                and val.value.id == "self"
                and val.attr.endswith("_api")
                and child.attr.startswith("get_")
            ):
                mapping[child.attr] = {
                    "wrapper": node.name,
                    "api_attr": val.attr,
                }
    return mapping


# ── Merge spec ↔ client ──────────────────────────────────────────────────


def _build_info(spec: dict[str, object], client_src: str) -> list[dict[str, str]]:
    """Combine spec GET endpoints with client wrapper method info."""
    eps = _get_endpoints(spec)
    cmap = _list_methods(client_src)
    matched: list[dict[str, str]] = []
    for ep in eps:
        info = cmap.get(str(ep["snake_id"]))
        if info is None:
            print(
                f"  ⚠  GET {ep['path']} ({ep['snake_id']}) — "
                "no list_* wrapper in client.py, skipping",
                file=sys.stderr,
            )
            continue
        result: dict[str, str] = {
            "path": str(ep["path"]),
            "operation_id": str(ep["operation_id"]),
            "snake_id": str(ep["snake_id"]),
            "tag": str(ep["tag"]),
            "response_model": str(ep["response_model"]),
            "wrapper": info["wrapper"],
            "api_attr": info["api_attr"],
        }
        resource = info["wrapper"].removeprefix("list_")
        result["resource"] = resource
        result["test_class"] = "TestList" + resource.replace("_", " ").title().replace(
            " ", ""
        )
        matched.append(result)
    return matched


# ── Code generation: test_integration.py ─────────────────────────────────


def _gen_integration(endpoints: list[dict[str, str]]) -> str:
    """Build the full contents of ``tests/test_integration.py``."""
    first_wrapper = endpoints[0]["wrapper"] if endpoints else "list_customers"

    # -- Module docstring + imports --------------------------------------
    header = (
        '"""Read-only integration tests for the Metquay API wrapper.\n'
        "\n"
        "These tests only call list/read endpoints. They never create, update, or\n"
        "delete resources. They require valid API credentials in .env or environment\n"
        "variables.\n"
        "\n"
        f"{_GENERATED}\n"
        '"""\n'
        "\n"
        "import pytest\n"
        "\n"
        "from openapi_client.exceptions import ApiException\n"
        "from tests.conftest import requires_credentials"
    )

    # -- TestAuthentication ----------------------------------------------
    auth = (
        "@requires_credentials\n"
        "class TestAuthentication:\n"
        "    def test_authenticate_returns_token(self, client):\n"
        '        """Explicitly calling authenticate() should return a valid token."""\n'
        "        response = client.authenticate()\n"
        "        assert response.access_token\n"
        '        assert response.token_type.lower() == "bearer"\n'
        "\n"
        "    def test_token_is_reused_on_subsequent_calls(self, client):\n"
        '        """After authenticating, the internal token should be reused."""\n'
        "        client.authenticate()\n"
        "        token_1 = client._token\n"
        "        # A list call should NOT trigger re-auth (token is fresh)\n"
        f"        client.{first_wrapper}(limit=1)\n"
        "        assert client._token == token_1"
    )

    # -- Per-endpoint test classes ---------------------------------------
    ep_classes: list[str] = []
    for ep in endpoints:
        w = ep["wrapper"]
        ep_classes.append(
            "@requires_credentials\n"
            f'class {ep["test_class"]}:\n'
            f"    def test_{w}_returns_list(self, client):\n"
            f"        try:\n"
            f"            result = client.{w}(limit=5)\n"
            f"        except ApiException as e:\n"
            f"            if e.status == 500:\n"
            f'                pytest.skip(f"Server error: {{e.reason}}")\n'
            f"            raise\n"
            "        assert isinstance(result, list)\n"
            "\n"
            f"    def test_{w}_pagination(self, client):\n"
            f"        try:\n"
            f"            page1 = client.{w}(first=0, limit=2)\n"
            f"            page2 = client.{w}(first=2, limit=2)\n"
            f"        except ApiException as e:\n"
            f"            if e.status == 500:\n"
            f'                pytest.skip(f"Server error: {{e.reason}}")\n'
            f"            raise\n"
            "        assert isinstance(page1, list)\n"
            "        assert isinstance(page2, list)\n"
            "        if len(page1) == 2 and len(page2) > 0:\n"
            "            assert page1 != page2\n"
            "\n"
            f"    def test_{w}_paginate_all(self, client):\n"
            f"        try:\n"
            f"            all_results = client.{w}(paginate_all=True)\n"
            f"        except ApiException as e:\n"
            f"            if e.status == 500:\n"
            f'                pytest.skip(f"Server error: {{e.reason}}")\n'
            f"            raise\n"
            f"        try:\n"
            f"            single_page = client.{w}(limit=50)\n"
            f"        except ApiException as e:\n"
            f"            if e.status == 500:\n"
            f'                pytest.skip(f"Server error: {{e.reason}}")\n'
            f"            raise\n"
            "        assert isinstance(all_results, list)\n"
            "        assert len(all_results) >= len(single_page)"
        )

    # Two blank lines between every top-level block
    return "\n\n\n".join([header, auth, *ep_classes]) + "\n"


# ── Code generation: test_response_shapes.py ─────────────────────────────


def _gen_shapes(endpoints: list[dict[str, str]]) -> str:
    """Build the full contents of ``tests/test_response_shapes.py``."""

    # -- Model imports (deduplicated, sorted) ----------------------------
    seen: set[str] = set()
    model_import_lines: list[str] = []
    for ep in sorted(endpoints, key=lambda e: e["response_model"]):
        cls = ep["response_model"]
        if cls in seen:
            continue
        seen.add(cls)
        mod = _cls_to_mod(cls)
        model_import_lines.append(f"from openapi_client.models.{mod} import {cls}")
    model_imports = "\n".join(model_import_lines)

    # -- Module docstring + imports --------------------------------------
    header = (
        '"""Verify that live API response shapes match the generated model fields.\n'
        "\n"
        "These tests catch spec-vs-reality drift by comparing the keys in the raw\n"
        "JSON response against the model's declared ``__properties``.  Two failure\n"
        "modes are detected:\n"
        "\n"
        "* **Unexpected keys** -- the API returns a field not declared in the spec.\n"
        "  This means ``from_dict()`` silently drops data that downstream callers\n"
        "  might need.\n"
        "* **Missing keys** -- the spec declares a field that the API never returns.\n"
        "  These are expected to some degree (optional fields) but a wholesale\n"
        "  mismatch signals a spec error.\n"
        "\n"
        f"{_GENERATED}\n"
        '"""\n'
        "\n"
        "import json\n"
        "from typing import Any, List, Set, Type\n"
        "\n"
        "import pytest\n"
        "\n"
        "from openapi_client.api_response import ApiResponse\n"
        "from openapi_client.exceptions import ApiException\n"
        f"{model_imports}\n"
        "from tests.conftest import requires_credentials"
    )

    # -- Helper functions ------------------------------------------------
    # Plain strings (NOT f-strings) to preserve runtime f-string literals
    raw_keys_fn = (
        "def _raw_keys_from(\n"
        "    api_response: ApiResponse,  # type: ignore[type-arg]\n"
        ") -> List[Set[str]]:\n"
        '    """Extract the set of JSON keys from each object in the raw response body."""\n'
        "    payload: Any = json.loads(api_response.raw_data)\n"
        "    if isinstance(payload, list):\n"
        "        return [set(item.keys()) for item in payload if isinstance(item, dict)]\n"
        "    if isinstance(payload, dict):\n"
        "        return [set(payload.keys())]\n"
        "    return []"
    )

    model_props_fn = (
        "def _model_properties(model_cls: Type[Any]) -> Set[str]:\n"
        '    """Return the set of properties declared on a generated model class."""\n'
        "    # The OpenAPI generator creates a ClassVar[List[str]] named __properties\n"
        "    # containing the JSON alias names for every field.\n"
        '    props: List[str] = getattr(model_cls, f"_{model_cls.__name__}__properties", [])\n'
        "    return set(props)"
    )

    # -- Test class header -----------------------------------------------
    class_header = (
        "@requires_credentials\n"
        "class TestResponseShapes:\n"
        '    """For each list endpoint, assert that live API keys match the model."""\n'
        "\n"
        "    @pytest.fixture(autouse=True)\n"
        "    def _ensure_authenticated(self, client):\n"
        '        """Guarantee the client has a valid token before raw API calls.\n'
        "\n"
        "        The high-level ``MetquayClient`` methods authenticate lazily, but\n"
        "        these tests hit the generated ``*_with_http_info`` methods directly,\n"
        "        which bypass that logic.  Without this fixture the tests fail when\n"
        "        run in isolation (e.g. from VS Code) because no prior test has\n"
        "        triggered authentication on the session-scoped client.\n"
        '        """\n'
        "        client.authenticate()"
    )

    # -- Per-endpoint test methods (inside the class) --------------------
    test_methods: list[str] = []
    for ep in endpoints:
        r = ep["resource"]
        m = ep["response_model"]
        a = ep["api_attr"]
        s = ep["snake_id"]
        test_methods.append(
            f"    def test_{r}_response_shape(self, client):\n"
            f"        try:\n"
            f"            resp: ApiResponse = (  # type: ignore[type-arg]\n"
            f"                client.{a}.{s}_with_http_info(\n"
            f"                    limit=1,\n"
            f"                )\n"
            f"            )\n"
            f"        except ApiException as e:\n"
            f"            if e.status == 500:\n"
            f'                pytest.skip(f"Server error: {{e.reason}}")\n'
            f"            raise\n"
            f"\n"
            f"        key_sets = _raw_keys_from(resp)\n"
            f"        if not key_sets:\n"
            f'            pytest.skip("No {r} in account")\n'
            f"\n"
            f"        expected = _model_properties({m})\n"
            f"        for actual_keys in key_sets:\n"
            f"            unexpected = actual_keys - expected\n"
            f"            assert (\n"
            f"                not unexpected\n"
            f'            ), f"API returned fields not in {m} model: {{unexpected}}"'
        )

    # Combine class header + methods with one blank line between each
    class_block = "\n\n".join([class_header, *test_methods])

    # Two blank lines between every top-level block
    return "\n\n\n".join([header, raw_keys_fn, model_props_fn, class_block]) + "\n"


# ── Main ─────────────────────────────────────────────────────────────────


def main() -> None:
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    client_src = CLIENT_PATH.read_text(encoding="utf-8")

    endpoints = _build_info(spec, client_src)
    if not endpoints:
        print("  ⚠  No matchable GET endpoints found — skipping.", file=sys.stderr)
        return

    print(f"  Found {len(endpoints)} GET endpoint(s):")
    for ep in endpoints:
        print(f"    {ep['path']} → {ep['wrapper']}()")

    INTEGRATION_PATH.write_text(_gen_integration(endpoints), encoding="utf-8")
    SHAPES_PATH.write_text(_gen_shapes(endpoints), encoding="utf-8")

    print(f"  ✓ {INTEGRATION_PATH.relative_to(ROOT)}")
    print(f"  ✓ {SHAPES_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
