# coding: utf-8

"""
    Metquay CRUD API

    Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter 

    The version of the OpenAPI document: 1.0.0-jgi
    Contact: support@metquay.atlassian.net
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class CustomerInstrumentRequest(BaseModel):
    """
    Request payload for creating or updating a customer instrument
    """ # noqa: E501
    name: StrictStr = Field(description="Descriptive name of the instrument")
    company_id: StrictStr = Field(description="Customer ID or code that owns this instrument", alias="companyId")
    serial_no: Optional[StrictStr] = Field(default=None, description="Manufacturer's unique serial number", alias="serialNo")
    tag_no: Optional[StrictStr] = Field(default=None, description="Internal asset tag or tracking number", alias="tagNo")
    make: Optional[StrictStr] = Field(default=None, description="Instrument manufacturer or brand")
    model: Optional[StrictStr] = Field(default=None, description="Manufacturer's model designation")
    range: Optional[StrictStr] = Field(default=None, description="Measurement range specifications")
    instrument_category_name: StrictStr = Field(description="Category this instrument belongs to", alias="instrumentCategoryName")
    calibration_frequency: Optional[StrictStr] = Field(default=None, description="Numerical value for calibration frequency", alias="calibrationFrequency")
    calibration_frequency_span: Optional[StrictStr] = Field(default=None, description="Time unit for calibration frequency", alias="calibrationFrequencySpan")
    instrument_status: Optional[StrictStr] = Field(default=None, description="Current operational status of the instrument", alias="instrumentStatus")
    last_received_date: Optional[datetime] = Field(default=None, description="Date and time when instrument was last received", alias="lastReceivedDate")
    last_delivered_date: Optional[datetime] = Field(default=None, description="Date and time when instrument was last delivered", alias="lastDeliveredDate")
    workspace_code: Optional[StrictStr] = Field(default=None, description="Workspace code (required only if workspace feature is enabled)", alias="workspaceCode")
    __properties: ClassVar[List[str]] = ["name", "companyId", "serialNo", "tagNo", "make", "model", "range", "instrumentCategoryName", "calibrationFrequency", "calibrationFrequencySpan", "instrumentStatus", "lastReceivedDate", "lastDeliveredDate", "workspaceCode"]

    @field_validator('calibration_frequency_span')
    def calibration_frequency_span_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['DAY', 'WEEK', 'MONTH', 'YEAR']):
            raise ValueError("must be one of enum values ('DAY', 'WEEK', 'MONTH', 'YEAR')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerInstrumentRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerInstrumentRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "companyId": obj.get("companyId"),
            "serialNo": obj.get("serialNo"),
            "tagNo": obj.get("tagNo"),
            "make": obj.get("make"),
            "model": obj.get("model"),
            "range": obj.get("range"),
            "instrumentCategoryName": obj.get("instrumentCategoryName"),
            "calibrationFrequency": obj.get("calibrationFrequency"),
            "calibrationFrequencySpan": obj.get("calibrationFrequencySpan"),
            "instrumentStatus": obj.get("instrumentStatus"),
            "lastReceivedDate": obj.get("lastReceivedDate"),
            "lastDeliveredDate": obj.get("lastDeliveredDate"),
            "workspaceCode": obj.get("workspaceCode")
        })
        return _obj


