# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (BaseModel, ConfigDict, Field, StrictBool, StrictFloat,
                      StrictInt, StrictStr, field_validator)
from typing_extensions import Self


class CustomerInstrumentResponse(BaseModel):
    """
    Customer instrument response object
    """  # noqa: E501

    id: Optional[StrictInt] = Field(
        default=None, description="Unique Metquay ID of the instrument"
    )
    barcode: Optional[StrictStr] = Field(
        default=None, description="Internal barcode identifier"
    )
    company_name: Optional[StrictStr] = Field(
        default=None,
        description="Name of the customer who owns the instrument",
        alias="companyName",
    )
    instrument_name: Optional[StrictStr] = Field(
        default=None,
        description="Descriptive name of the instrument",
        alias="instrumentName",
    )
    instrument_category: Optional[StrictStr] = Field(
        default=None,
        description="Category of the instrument",
        alias="instrumentCategory",
    )
    item_name: Optional[StrictStr] = Field(
        default=None, description="Associated catalog item name", alias="itemName"
    )
    make: Optional[StrictStr] = Field(
        default=None, description="Instrument manufacturer"
    )
    model: Optional[StrictStr] = Field(default=None, description="Instrument model")
    range: Optional[StrictStr] = Field(default=None, description="Measurement range")
    type: Optional[StrictStr] = Field(
        default=None, description="Instrument type/variant"
    )
    tolerance: Optional[StrictStr] = Field(
        default=None, description="Accuracy tolerance specification"
    )
    serial_no: Optional[StrictStr] = Field(
        default=None, description="Manufacturer serial number", alias="serialNo"
    )
    tag_no: Optional[StrictStr] = Field(
        default=None, description="Internal asset tag number", alias="tagNo"
    )
    control_no: Optional[StrictStr] = Field(
        default=None, description="Quality control tracking number", alias="controlNo"
    )
    calibration_frequency: Optional[StrictStr] = Field(
        default=None,
        description="Calibration frequency value",
        alias="calibrationFrequency",
    )
    workspace_code: Optional[StrictStr] = Field(
        default=None, description="Workspace code", alias="workspaceCode"
    )
    calibration_frequency_span: Optional[StrictStr] = Field(
        default=None,
        description="Calibration frequency time unit",
        alias="calibrationFrequencySpan",
    )
    calibrated_date: Optional[date] = Field(
        default=None,
        description="Most recent calibration date (MM-dd-yyyy)",
        alias="calibratedDate",
    )
    due_date: Optional[date] = Field(
        default=None,
        description="Next calibration due date (MM-dd-yyyy)",
        alias="dueDate",
    )
    active: Optional[StrictBool] = Field(
        default=None, description="Instrument active status"
    )
    parent_tag_no: Optional[StrictStr] = Field(
        default=None,
        description="Parent instrument tag number (for component instruments)",
        alias="parentTagNo",
    )
    department_name: Optional[StrictStr] = Field(
        default=None,
        description="Department or location where instrument is assigned",
        alias="departmentName",
    )
    verification_due_date: Optional[date] = Field(
        default=None,
        description="Intermediate verification due date (MM-dd-yyyy)",
        alias="verificationDueDate",
    )
    calibration_cost: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Cost of calibration service", alias="calibrationCost"
    )
    is_calibrated_externally: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if calibration is performed by external vendor",
        alias="isCalibratedExternally",
    )
    calibration_vendor: Optional[StrictStr] = Field(
        default=None,
        description="Name of calibration service provider",
        alias="calibrationVendor",
    )
    remarks: Optional[StrictStr] = Field(
        default=None, description="General remarks about the instrument"
    )
    instrument_notes: Optional[StrictStr] = Field(
        default=None, description="Internal maintenance notes", alias="instrumentNotes"
    )
    is_mobile: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if instrument is portable for field use",
        alias="isMobile",
    )
    is_calibration_required: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if periodic calibration is required",
        alias="isCalibrationRequired",
    )
    last_received_date: Optional[date] = Field(
        default=None,
        description="Date instrument was last received (MM-dd-yyyy)",
        alias="lastReceivedDate",
    )
    last_delivered_date: Optional[date] = Field(
        default=None,
        description="Date instrument was last delivered (MM-dd-yyyy)",
        alias="lastDeliveredDate",
    )
    calibration_status: Optional[StrictStr] = Field(
        default=None,
        description="Current calibration status",
        alias="calibrationStatus",
    )
    received_condition: Optional[StrictStr] = Field(
        default=None,
        description="Condition assessment when received",
        alias="receivedCondition",
    )
    audited_date: Optional[date] = Field(
        default=None,
        description="Date of last quality audit (MM-dd-yyyy)",
        alias="auditedDate",
    )
    certificate_url: Optional[StrictStr] = Field(
        default=None,
        description="URL to the latest calibration certificate",
        alias="certificateUrl",
    )
    project_names: Optional[List[StrictStr]] = Field(
        default=None,
        description="Associated project names or codes",
        alias="projectNames",
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "barcode",
        "companyName",
        "instrumentName",
        "instrumentCategory",
        "itemName",
        "make",
        "model",
        "range",
        "type",
        "tolerance",
        "serialNo",
        "tagNo",
        "controlNo",
        "calibrationFrequency",
        "workspaceCode",
        "calibrationFrequencySpan",
        "calibratedDate",
        "dueDate",
        "active",
        "parentTagNo",
        "departmentName",
        "verificationDueDate",
        "calibrationCost",
        "isCalibratedExternally",
        "calibrationVendor",
        "remarks",
        "instrumentNotes",
        "isMobile",
        "isCalibrationRequired",
        "lastReceivedDate",
        "lastDeliveredDate",
        "calibrationStatus",
        "receivedCondition",
        "auditedDate",
        "certificateUrl",
        "projectNames",
    ]

    @field_validator("calibration_frequency_span")
    def calibration_frequency_span_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["DAY", "WEEK", "MONTH", "YEAR"]):
            raise ValueError(
                "must be one of enum values ('DAY', 'WEEK', 'MONTH', 'YEAR')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerInstrumentResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerInstrumentResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "barcode": obj.get("barcode"),
                "companyName": obj.get("companyName"),
                "instrumentName": obj.get("instrumentName"),
                "instrumentCategory": obj.get("instrumentCategory"),
                "itemName": obj.get("itemName"),
                "make": obj.get("make"),
                "model": obj.get("model"),
                "range": obj.get("range"),
                "type": obj.get("type"),
                "tolerance": obj.get("tolerance"),
                "serialNo": obj.get("serialNo"),
                "tagNo": obj.get("tagNo"),
                "controlNo": obj.get("controlNo"),
                "calibrationFrequency": obj.get("calibrationFrequency"),
                "workspaceCode": obj.get("workspaceCode"),
                "calibrationFrequencySpan": obj.get("calibrationFrequencySpan"),
                "calibratedDate": obj.get("calibratedDate"),
                "dueDate": obj.get("dueDate"),
                "active": obj.get("active"),
                "parentTagNo": obj.get("parentTagNo"),
                "departmentName": obj.get("departmentName"),
                "verificationDueDate": obj.get("verificationDueDate"),
                "calibrationCost": obj.get("calibrationCost"),
                "isCalibratedExternally": obj.get("isCalibratedExternally"),
                "calibrationVendor": obj.get("calibrationVendor"),
                "remarks": obj.get("remarks"),
                "instrumentNotes": obj.get("instrumentNotes"),
                "isMobile": obj.get("isMobile"),
                "isCalibrationRequired": obj.get("isCalibrationRequired"),
                "lastReceivedDate": obj.get("lastReceivedDate"),
                "lastDeliveredDate": obj.get("lastDeliveredDate"),
                "calibrationStatus": obj.get("calibrationStatus"),
                "receivedCondition": obj.get("receivedCondition"),
                "auditedDate": obj.get("auditedDate"),
                "certificateUrl": obj.get("certificateUrl"),
                "projectNames": obj.get("projectNames"),
            }
        )
        return _obj
