# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Any, ClassVar, Dict, List, Optional, Set, Union

from pydantic import (BaseModel, ConfigDict, Field, StrictBool, StrictFloat,
                      StrictInt, StrictStr)
from typing_extensions import Self


class CustomerResponse(BaseModel):
    """
    Customer response object
    """  # noqa: E501

    id: Optional[StrictInt] = Field(
        default=None, description="Unique Metquay ID of the customer"
    )
    parent_company_code: Optional[StrictStr] = Field(
        default=None,
        description="Parent company code (if this customer is a subsidiary)",
        alias="parentCompanyCode",
    )
    company_code: Optional[StrictStr] = Field(
        default=None,
        description="Unique identifier for the customer",
        alias="companyCode",
    )
    is_inactive: Optional[StrictBool] = Field(
        default=None,
        description="Customer status - false for active, true for inactive",
        alias="isInactive",
    )
    company_name: Optional[StrictStr] = Field(
        default=None,
        description="Legal name of the customer organization",
        alias="companyName",
    )
    email: Optional[StrictStr] = Field(
        default=None, description="Primary contact email address"
    )
    website: Optional[StrictStr] = Field(
        default=None, description="Customer website URL"
    )
    payment_method: Optional[StrictStr] = Field(
        default=None, description="Preferred payment method", alias="paymentMethod"
    )
    phone: Optional[StrictStr] = Field(default=None, description="Primary phone number")
    mobile: Optional[StrictStr] = Field(default=None, description="Mobile phone number")
    fax: Optional[StrictStr] = Field(default=None, description="Fax number")
    other: Optional[StrictStr] = Field(
        default=None, description="Alternate phone number"
    )
    activate_alerts: Optional[StrictBool] = Field(
        default=None, description="Alert notification status", alias="activateAlerts"
    )
    workspace_code: Optional[StrictStr] = Field(
        default=None, description="Workspace code", alias="workspaceCode"
    )
    has_billing_address: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if billing address exists",
        alias="hasBillingAddress",
    )
    billing_addr1: Optional[StrictStr] = Field(
        default=None, description="Billing address line 1", alias="billingAddr1"
    )
    billing_addr2: Optional[StrictStr] = Field(
        default=None, description="Billing address line 2", alias="billingAddr2"
    )
    billing_city: Optional[StrictStr] = Field(
        default=None, description="Billing address city", alias="billingCity"
    )
    billing_state: Optional[StrictStr] = Field(
        default=None, description="Billing address state/province", alias="billingState"
    )
    billing_zip: Optional[StrictStr] = Field(
        default=None, description="Billing address postal/zip code", alias="billingZip"
    )
    billing_country: Optional[StrictStr] = Field(
        default=None, description="Billing address country", alias="billingCountry"
    )
    billing_phone1: Optional[StrictStr] = Field(
        default=None,
        description="Billing department phone number",
        alias="billingPhone1",
    )
    billing_phone2: Optional[StrictStr] = Field(
        default=None,
        description="Billing department alternate phone",
        alias="billingPhone2",
    )
    has_shipping_address: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if shipping address exists",
        alias="hasShippingAddress",
    )
    shipping_addr1: Optional[StrictStr] = Field(
        default=None, description="Shipping address line 1", alias="shippingAddr1"
    )
    shipping_addr2: Optional[StrictStr] = Field(
        default=None, description="Shipping address line 2", alias="shippingAddr2"
    )
    shipping_city: Optional[StrictStr] = Field(
        default=None, description="Shipping address city", alias="shippingCity"
    )
    shipping_state: Optional[StrictStr] = Field(
        default=None,
        description="Shipping address state/province",
        alias="shippingState",
    )
    shipping_zip: Optional[StrictStr] = Field(
        default=None,
        description="Shipping address postal/zip code",
        alias="shippingZip",
    )
    shipping_country: Optional[StrictStr] = Field(
        default=None, description="Shipping address country", alias="shippingCountry"
    )
    customer_specific_requirements: Optional[StrictStr] = Field(
        default=None,
        description="Customer specific delivery or service requirements",
        alias="customerSpecificRequirements",
    )
    notes: Optional[StrictStr] = Field(
        default=None, description="General notes about the customer"
    )
    short_name: Optional[StrictStr] = Field(
        default=None,
        description="Short name or alias for display purposes",
        alias="shortName",
    )
    is_taxable: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if customer is subject to tax",
        alias="isTaxable",
    )
    tax_code: Optional[StrictStr] = Field(
        default=None, description="Tax exemption code or tax ID", alias="taxCode"
    )
    opening_balance: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None, description="Opening account balance", alias="openingBalance"
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "parentCompanyCode",
        "companyCode",
        "isInactive",
        "companyName",
        "email",
        "website",
        "paymentMethod",
        "phone",
        "mobile",
        "fax",
        "other",
        "activateAlerts",
        "workspaceCode",
        "hasBillingAddress",
        "billingAddr1",
        "billingAddr2",
        "billingCity",
        "billingState",
        "billingZip",
        "billingCountry",
        "billingPhone1",
        "billingPhone2",
        "hasShippingAddress",
        "shippingAddr1",
        "shippingAddr2",
        "shippingCity",
        "shippingState",
        "shippingZip",
        "shippingCountry",
        "customerSpecificRequirements",
        "notes",
        "shortName",
        "isTaxable",
        "taxCode",
        "openingBalance",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "parentCompanyCode": obj.get("parentCompanyCode"),
                "companyCode": obj.get("companyCode"),
                "isInactive": obj.get("isInactive"),
                "companyName": obj.get("companyName"),
                "email": obj.get("email"),
                "website": obj.get("website"),
                "paymentMethod": obj.get("paymentMethod"),
                "phone": obj.get("phone"),
                "mobile": obj.get("mobile"),
                "fax": obj.get("fax"),
                "other": obj.get("other"),
                "activateAlerts": obj.get("activateAlerts"),
                "workspaceCode": obj.get("workspaceCode"),
                "hasBillingAddress": obj.get("hasBillingAddress"),
                "billingAddr1": obj.get("billingAddr1"),
                "billingAddr2": obj.get("billingAddr2"),
                "billingCity": obj.get("billingCity"),
                "billingState": obj.get("billingState"),
                "billingZip": obj.get("billingZip"),
                "billingCountry": obj.get("billingCountry"),
                "billingPhone1": obj.get("billingPhone1"),
                "billingPhone2": obj.get("billingPhone2"),
                "hasShippingAddress": obj.get("hasShippingAddress"),
                "shippingAddr1": obj.get("shippingAddr1"),
                "shippingAddr2": obj.get("shippingAddr2"),
                "shippingCity": obj.get("shippingCity"),
                "shippingState": obj.get("shippingState"),
                "shippingZip": obj.get("shippingZip"),
                "shippingCountry": obj.get("shippingCountry"),
                "customerSpecificRequirements": obj.get("customerSpecificRequirements"),
                "notes": obj.get("notes"),
                "shortName": obj.get("shortName"),
                "isTaxable": obj.get("isTaxable"),
                "taxCode": obj.get("taxCode"),
                "openingBalance": obj.get("openingBalance"),
            }
        )
        return _obj
