# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (BaseModel, ConfigDict, Field, StrictBool, StrictInt,
                      StrictStr, field_validator)
from typing_extensions import Self


class WorkRequest(BaseModel):
    """
    Request payload for creating or updating a work
    """  # noqa: E501

    customer_instrument_id: StrictInt = Field(
        description="Numeric ID of the customer instrument being calibrated/tested",
        alias="customerInstrumentId",
    )
    in_date: Optional[datetime] = Field(
        default=None,
        description="Date and time when instrument was received for work",
        alias="inDate",
    )
    accreditation: Optional[StrictBool] = Field(
        default=False,
        description="true for ISO 17025 accredited work, false for non-accredited",
    )
    compliance_required: Optional[StrictBool] = Field(
        default=False,
        description="true if regulatory compliance verification is required",
        alias="complianceRequired",
    )
    site_job: Optional[StrictBool] = Field(
        default=False,
        description="true for on-site work at customer facility, false for in-lab",
        alias="siteJob",
    )
    outsource: Optional[StrictBool] = Field(
        default=False, description="true if work is subcontracted to external provider"
    )
    customer_specific_requirements: Optional[StrictStr] = Field(
        default=None,
        description="Special requirements or instructions from customer",
        alias="customerSpecificRequirements",
    )
    scope: Optional[StrictStr] = Field(
        default=None, description="Detailed description of work to be performed"
    )
    certificate_address: Optional[StrictStr] = Field(
        default=None,
        description="Complete address to be printed on calibration certificate",
        alias="certificateAddress",
    )
    remarks: Optional[StrictStr] = Field(
        default=None, description="General remarks about the work order"
    )
    work_flow_type: Optional[StrictStr] = Field(
        default="Calibration",
        description="Type of workflow to apply",
        alias="workFlowType",
    )
    delivery_date: Optional[datetime] = Field(
        default=None,
        description="Target completion and delivery date",
        alias="deliveryDate",
    )
    sales_order_no: Optional[StrictStr] = Field(
        default=None,
        description="Customer purchase order or sales order reference",
        alias="salesOrderNo",
    )
    workspace_code: Optional[StrictStr] = Field(
        default=None,
        description="Workspace code (required only if workspace feature is enabled)",
        alias="workspaceCode",
    )
    sub_con_details: Optional[StrictStr] = Field(
        default=None,
        description="Additional details for subcontracted work",
        alias="subConDetails",
    )
    __properties: ClassVar[List[str]] = [
        "customerInstrumentId",
        "inDate",
        "accreditation",
        "complianceRequired",
        "siteJob",
        "outsource",
        "customerSpecificRequirements",
        "scope",
        "certificateAddress",
        "remarks",
        "workFlowType",
        "deliveryDate",
        "salesOrderNo",
        "workspaceCode",
        "subConDetails",
    ]

    @field_validator("work_flow_type")
    def work_flow_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(["Calibration", "Testing", "Evaluation"]):
            raise ValueError(
                "must be one of enum values ('Calibration', 'Testing', 'Evaluation')"
            )
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "customerInstrumentId": obj.get("customerInstrumentId"),
                "inDate": obj.get("inDate"),
                "accreditation": (
                    obj.get("accreditation")
                    if obj.get("accreditation") is not None
                    else False
                ),
                "complianceRequired": (
                    obj.get("complianceRequired")
                    if obj.get("complianceRequired") is not None
                    else False
                ),
                "siteJob": (
                    obj.get("siteJob") if obj.get("siteJob") is not None else False
                ),
                "outsource": (
                    obj.get("outsource") if obj.get("outsource") is not None else False
                ),
                "customerSpecificRequirements": obj.get("customerSpecificRequirements"),
                "scope": obj.get("scope"),
                "certificateAddress": obj.get("certificateAddress"),
                "remarks": obj.get("remarks"),
                "workFlowType": (
                    obj.get("workFlowType")
                    if obj.get("workFlowType") is not None
                    else "Calibration"
                ),
                "deliveryDate": obj.get("deliveryDate"),
                "salesOrderNo": obj.get("salesOrderNo"),
                "workspaceCode": obj.get("workspaceCode"),
                "subConDetails": obj.get("subConDetails"),
            }
        )
        return _obj
