# coding: utf-8

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from datetime import date, datetime
from typing import Any, ClassVar, Dict, List, Optional, Set

from pydantic import (BaseModel, ConfigDict, Field, StrictBool, StrictInt,
                      StrictStr, field_validator)
from typing_extensions import Self


class WorkResponse(BaseModel):
    """
    Work response object
    """  # noqa: E501

    id: Optional[StrictInt] = Field(
        default=None, description="Unique Metquay ID of the work"
    )
    work_no: Optional[StrictStr] = Field(
        default=None, description="Unique work order number", alias="workNo"
    )
    customer_instrument_id: Optional[StrictInt] = Field(
        default=None,
        description="Numeric ID of the customer instrument",
        alias="customerInstrumentId",
    )
    in_date: Optional[date] = Field(
        default=None, description="Date instrument was received", alias="inDate"
    )
    accreditation: Optional[StrictBool] = Field(
        default=None, description="Indicates if work is ISO 17025 accredited"
    )
    compliance_required: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if regulatory compliance verification is required",
        alias="complianceRequired",
    )
    site_job: Optional[StrictBool] = Field(
        default=None,
        description="Indicates if work was performed on-site",
        alias="siteJob",
    )
    outsource: Optional[StrictBool] = Field(
        default=None, description="Indicates if work was subcontracted"
    )
    customer_specific_requirements: Optional[StrictStr] = Field(
        default=None,
        description="Customer special requirements",
        alias="customerSpecificRequirements",
    )
    scope: Optional[StrictStr] = Field(
        default=None, description="Detailed scope of work"
    )
    certificate_address: Optional[StrictStr] = Field(
        default=None,
        description="Complete address printed on certificate",
        alias="certificateAddress",
    )
    remarks: Optional[StrictStr] = Field(default=None, description="Work order remarks")
    work_flow_type: Optional[StrictStr] = Field(
        default=None, description="Type of workflow performed", alias="workFlowType"
    )
    delivery_date: Optional[date] = Field(
        default=None, description="Target delivery date", alias="deliveryDate"
    )
    sales_order_no: Optional[StrictStr] = Field(
        default=None,
        description="Customer purchase order or sales order reference",
        alias="salesOrderNo",
    )
    workspace_code: Optional[StrictStr] = Field(
        default=None, description="Workspace code", alias="workspaceCode"
    )
    sub_con_details: Optional[StrictStr] = Field(
        default=None,
        description="Subcontractor details if outsourced",
        alias="subConDetails",
    )
    customer: Optional[StrictStr] = Field(default=None, description="Customer name")
    instrument_name: Optional[StrictStr] = Field(
        default=None, description="Instrument name", alias="instrumentName"
    )
    instrument_serial_no: Optional[StrictStr] = Field(
        default=None, description="Instrument serial number", alias="instrumentSerialNo"
    )
    instrument_tag_no: Optional[StrictStr] = Field(
        default=None, description="Instrument tag number", alias="instrumentTagNo"
    )
    instrument_barcode: Optional[StrictStr] = Field(
        default=None, description="Instrument barcode", alias="instrumentBarcode"
    )
    instrument_category_name: Optional[StrictStr] = Field(
        default=None, description="Instrument category", alias="instrumentCategoryName"
    )
    item_description: Optional[StrictStr] = Field(
        default=None, description="Catalog item description", alias="itemDescription"
    )
    department_name: Optional[StrictStr] = Field(
        default=None,
        description="Department performing the work",
        alias="departmentName",
    )
    status: Optional[StrictStr] = Field(default=None, description="Current work status")
    report_type: Optional[StrictStr] = Field(
        default=None,
        description="Type of report/certificate generated",
        alias="reportType",
    )
    accreditation_type: Optional[StrictStr] = Field(
        default=None,
        description="Accreditation standard applied",
        alias="accreditationType",
    )
    procedure: Optional[StrictStr] = Field(
        default=None, description="Calibration procedure used"
    )
    technician: Optional[StrictStr] = Field(
        default=None, description="Primary technician assigned"
    )
    work_date: Optional[date] = Field(
        default=None,
        description="Date work was performed (MM-dd-yyyy)",
        alias="workDate",
    )
    due_date: Optional[date] = Field(
        default=None, description="Original due date (MM-dd-yyyy)", alias="dueDate"
    )
    revision_no: Optional[StrictInt] = Field(
        default=None,
        description="Revision number of the work order",
        alias="revisionNo",
    )
    certificate_no: Optional[StrictStr] = Field(
        default=None, description="Generated certificate number", alias="certificateNo"
    )
    finished_date: Optional[date] = Field(
        default=None,
        description="Date work was completed (MM-dd-yyyy)",
        alias="finishedDate",
    )
    finished_by: Optional[StrictStr] = Field(
        default=None,
        description="Technician who completed the work",
        alias="finishedBy",
    )
    sales_person: Optional[StrictStr] = Field(
        default=None, description="Sales representative", alias="salesPerson"
    )
    recommended_due_date: Optional[date] = Field(
        default=None,
        description="Recommended next calibration due date (MM-dd-yyyy)",
        alias="recommendedDueDate",
    )
    calibrated_date: Optional[date] = Field(
        default=None,
        description="Actual calibration date (MM-dd-yyyy)",
        alias="calibratedDate",
    )
    work_start_date: Optional[date] = Field(
        default=None, description="Work start date (MM-dd-yyyy)", alias="workStartDate"
    )
    customer_po_no: Optional[StrictStr] = Field(
        default=None, description="Customer purchase order number", alias="customerPoNo"
    )
    so_description: Optional[StrictStr] = Field(
        default=None, description="Sales order description", alias="soDescription"
    )
    workspace: Optional[StrictStr] = Field(default=None, description="Workspace name")
    job_type: Optional[StrictStr] = Field(
        default=None, description="Job type classification", alias="jobType"
    )
    __properties: ClassVar[List[str]] = [
        "id",
        "workNo",
        "customerInstrumentId",
        "inDate",
        "accreditation",
        "complianceRequired",
        "siteJob",
        "outsource",
        "customerSpecificRequirements",
        "scope",
        "certificateAddress",
        "remarks",
        "workFlowType",
        "deliveryDate",
        "salesOrderNo",
        "workspaceCode",
        "subConDetails",
        "customer",
        "instrumentName",
        "instrumentSerialNo",
        "instrumentTagNo",
        "instrumentBarcode",
        "instrumentCategoryName",
        "itemDescription",
        "departmentName",
        "status",
        "reportType",
        "accreditationType",
        "procedure",
        "technician",
        "workDate",
        "dueDate",
        "revisionNo",
        "certificateNo",
        "finishedDate",
        "finishedBy",
        "salesPerson",
        "recommendedDueDate",
        "calibratedDate",
        "workStartDate",
        "customerPoNo",
        "soDescription",
        "workspace",
        "jobType",
    ]

    @field_validator(
        "in_date",
        "delivery_date",
        "work_date",
        "due_date",
        "finished_date",
        "recommended_due_date",
        "calibrated_date",
        "work_start_date",
        mode="before",
    )
    @classmethod
    def _parse_date(cls, value):
        """Parse MM-dd-yyyy date strings from the API."""
        if value is None or isinstance(value, date):
            return value
        if isinstance(value, str):
            for fmt in ("%m-%d-%Y", "%Y-%m-%d"):
                try:
                    return datetime.strptime(value, fmt).date()
                except ValueError:
                    continue
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "id": obj.get("id"),
                "workNo": obj.get("workNo"),
                "customerInstrumentId": obj.get("customerInstrumentId"),
                "inDate": obj.get("inDate"),
                "accreditation": obj.get("accreditation"),
                "complianceRequired": obj.get("complianceRequired"),
                "siteJob": obj.get("siteJob"),
                "outsource": obj.get("outsource"),
                "customerSpecificRequirements": obj.get("customerSpecificRequirements"),
                "scope": obj.get("scope"),
                "certificateAddress": obj.get("certificateAddress"),
                "remarks": obj.get("remarks"),
                "workFlowType": obj.get("workFlowType"),
                "deliveryDate": obj.get("deliveryDate"),
                "salesOrderNo": obj.get("salesOrderNo"),
                "workspaceCode": obj.get("workspaceCode"),
                "subConDetails": obj.get("subConDetails"),
                "customer": obj.get("customer"),
                "instrumentName": obj.get("instrumentName"),
                "instrumentSerialNo": obj.get("instrumentSerialNo"),
                "instrumentTagNo": obj.get("instrumentTagNo"),
                "instrumentBarcode": obj.get("instrumentBarcode"),
                "instrumentCategoryName": obj.get("instrumentCategoryName"),
                "itemDescription": obj.get("itemDescription"),
                "departmentName": obj.get("departmentName"),
                "status": obj.get("status"),
                "reportType": obj.get("reportType"),
                "accreditationType": obj.get("accreditationType"),
                "procedure": obj.get("procedure"),
                "technician": obj.get("technician"),
                "workDate": obj.get("workDate"),
                "dueDate": obj.get("dueDate"),
                "revisionNo": obj.get("revisionNo"),
                "certificateNo": obj.get("certificateNo"),
                "finishedDate": obj.get("finishedDate"),
                "finishedBy": obj.get("finishedBy"),
                "salesPerson": obj.get("salesPerson"),
                "recommendedDueDate": obj.get("recommendedDueDate"),
                "calibratedDate": obj.get("calibratedDate"),
                "workStartDate": obj.get("workStartDate"),
                "customerPoNo": obj.get("customerPoNo"),
                "soDescription": obj.get("soDescription"),
                "workspace": obj.get("workspace"),
                "jobType": obj.get("jobType"),
            }
        )
        return _obj
