# coding: utf-8

# flake8: noqa

"""
Metquay CRUD API

Enterprise CRUD API for managing Metquay calibration management system entities. Provides complete CRUD operations for customers, instrument categories, customer instruments, and works.  ## Authentication Flow 1. Call `/authenticate` with your access/secret keys 2. Receive Bearer token (valid for 15 minutes) 3. Include token in `Authorization: Bearer {token}` header for all subsequent requests 4. Re-authenticate when token expires  ## Rate Limiting - **100 requests per minute** per API client - Exceeding limit returns 429 Too Many Requests - Contact support for rate limit increases  ## Idempotency - PUT and DELETE operations are idempotent (safe to retry) - POST operations are NOT idempotent (retry may create duplicates)  ## Pagination - List endpoints support pagination via `first` and `limit` query parameters - `first`: Starting index (default: 0, minimum: 0) - `limit`: Number of records to return (default: 50)  ## Workspace Feature - `workspaceCode` is optional and only required if the workspace feature is enabled for your organization - If workspace feature is not enabled, omit this parameter

The version of the OpenAPI document: 1.0.0-jgi
Contact: support@metquay.atlassian.net
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from openapi_client.api.authenticate_api import AuthenticateApi
from openapi_client.api.customerinstruments_api import CustomerinstrumentsApi
from openapi_client.api.customers_api import CustomersApi
from openapi_client.api.instrumentcategories_api import InstrumentcategoriesApi
from openapi_client.api.works_api import WorksApi
from openapi_client.api_client import ApiClient
# import ApiClient
from openapi_client.api_response import ApiResponse
from openapi_client.configuration import Configuration
from openapi_client.exceptions import (ApiAttributeError, ApiException,
                                       ApiKeyError, ApiTypeError,
                                       ApiValueError, OpenApiException)
# import models into sdk package
from openapi_client.models.authentication_request import AuthenticationRequest
from openapi_client.models.authentication_response import \
    AuthenticationResponse
from openapi_client.models.created_response import CreatedResponse
from openapi_client.models.customer_instrument_request import \
    CustomerInstrumentRequest
from openapi_client.models.customer_instrument_response import \
    CustomerInstrumentResponse
from openapi_client.models.customer_request import CustomerRequest
from openapi_client.models.customer_response import CustomerResponse
from openapi_client.models.error_response import ErrorResponse
from openapi_client.models.instrument_category_request import \
    InstrumentCategoryRequest
from openapi_client.models.work_request import WorkRequest
from openapi_client.models.work_response import WorkResponse
